import { StyleSheet } from "react-native";

export const gameStyles = StyleSheet.create({
  gameContainer: {
    flex: 1,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    paddingHorizontal: 10,
    paddingTop: 8,
    gap: 9,
  },
  gameTopBar: {
    minHeight: 58,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  gameInfoPill: {
    backgroundColor: "rgba(6,20,15,0.72)",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minWidth: 80,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  gameInfoLabel: {
    color: "#d8c5a7",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  gameInfoValue: {
    color: "#ffffff",
    fontSize: 19,
    fontWeight: "900",
  },
  turnBanner: {
    flex: 1,
    backgroundColor: "rgba(245,239,228,0.96)",
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(216,197,167,0.7)",
  },
  turnBannerActive: {
    backgroundColor: "#dcefe2",
    borderColor: "#8fc9a6",
  },
  turnBannerText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 14,
    textAlign: "center",
  },
  exitMiniButton: {
    backgroundColor: "rgba(239,68,68,0.16)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.35)",
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  exitMiniText: {
    color: "#fecaca",
    fontWeight: "900",
    fontSize: 12,
  },
  tableWrapper: {
    flex: 1,
    minHeight: 250,
  },
  woodTable: {
    flex: 1,
    borderRadius: 32,
    padding: 8,
    borderWidth: 2,
    borderColor: "#6f5138",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 12,
  },
  tableShadow: {
    flex: 1,
    borderRadius: 27,
    backgroundColor: "rgba(0,0,0,0.26)",
    padding: 5,
  },
  greenTable: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#0b2b21",
    position: "relative",
    overflow: "hidden",
    padding: 12,
    justifyContent: "space-between",
    gap: 10,
  },
  tableGlow: {
    position: "absolute",
    left: 34,
    right: 34,
    top: 72,
    bottom: 68,
    borderRadius: 999,
    backgroundColor: "rgba(245,239,228,0.08)",
  },
  tableInnerLine: {
    position: "absolute",
    left: 12,
    right: 12,
    top: 12,
    bottom: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.12)",
  },
  opponentRail: {
    flexDirection: "row",
    gap: 8,
    minHeight: 62,
    alignItems: "flex-start",
    justifyContent: "center",
    zIndex: 3,
  },
  opponentRailCompact: {
    minHeight: 50,
    gap: 6,
  },
  tableCenterZone: {
    flex: 1,
    minHeight: 142,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    zIndex: 2,
  },
  tableCenterZoneCompact: {
    minHeight: 104,
    paddingVertical: 0,
  },
  pileStage: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 28,
    backgroundColor: "rgba(4,17,13,0.34)",
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.16)",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 7,
    },
  },
  pileStageActive: {
    borderColor: "#86efac",
    backgroundColor: "rgba(22,101,52,0.28)",
  },
  pileStageCompact: {
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 23,
  },
  tableDropHint: {
    position: "absolute",
    top: -15,
    alignSelf: "center",
    backgroundColor: "#dcfce7",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#86efac",
    zIndex: 20,
  },
  tableDropHintText: {
    color: "#166534",
    fontSize: 10,
    fontWeight: "900",
  },
  pileSlot: {
    alignItems: "center",
    gap: 7,
  },
  pileDivider: {
    width: 1,
    height: 92,
    backgroundColor: "rgba(245,239,228,0.16)",
  },
  pileDividerCompact: {
    height: 74,
  },
  pileCaption: {
    color: "rgba(245,239,228,0.74)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  deckCard: {
    width: 78,
    height: 112,
    borderRadius: 18,
    backgroundColor: "#10251d",
    borderWidth: 2,
    borderColor: "#d8c5a7",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.38,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 8,
  },
  deckCardReady: {
    borderColor: "#facc15",
    shadowColor: "#facc15",
    shadowOpacity: 0.34,
  },
  deckCardCompact: {
    width: 64,
    height: 92,
    borderRadius: 15,
  },
  disabledDeck: {
    opacity: 0.55,
  },
  deckBackImage: {
    position: "absolute",
    width: 78,
    height: 112,
    borderRadius: 16,
    opacity: 0.9,
  },
  deckBackImageCompact: {
    width: 64,
    height: 92,
    borderRadius: 13,
  },
  deckLabel: {
    color: "#fff7ed",
    fontWeight: "900",
    marginTop: 9,
    fontSize: 12,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffset: {
      width: 0,
      height: 1,
    },
    textShadowRadius: 3,
  },
  discardCard: {
    width: 86,
    height: 122,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    shadowColor: "#000",
    shadowOpacity: 0.34,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 8,
  },
  discardCardCompact: {
    width: 72,
    height: 102,
  },
  tableCardImage: {
    width: 86,
    height: 122,
  },
  tableCardImageCompact: {
    width: 72,
    height: 102,
  },
  tableHud: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    zIndex: 3,
    backgroundColor: "rgba(4,17,13,0.38)",
    borderRadius: 22,
    padding: 4,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.12)",
  },
  tableHudPill: {
    backgroundColor: "rgba(245,239,228,0.96)",
    borderRadius: 999,
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.10)",
  },
  directionText: {
    fontSize: 25,
    fontWeight: "900",
    color: "#17352a",
  },
  tableHudStatus: {
    flex: 1,
    backgroundColor: "rgba(245,239,228,0.96)",
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.10)",
    alignItems: "center",
  },
  statusInfoText: {
    color: "#374151",
    fontWeight: "900",
    fontSize: 11,
  },
  penaltyBubble: {
    backgroundColor: "#b93832",
    borderRadius: 999,
    minWidth: 44,
    height: 42,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  penaltyBubbleText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
  },
  winRibbon: {
    position: "absolute",
    left: -30,
    right: -30,
    top: "45%",
    backgroundColor: "rgba(245,239,228,0.96)",
    paddingVertical: 16,
    transform: [{ rotate: "-10deg" }],
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  winRibbonText: {
    textAlign: "center",
    color: "#17352a",
    fontSize: 20,
    fontWeight: "900",
  },
  opponentSeat: {
    flexGrow: 0,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: 164,
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(6,20,15,0.68)",
    borderRadius: 20,
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 6,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.52)",
    position: "relative",
  },
  opponentSeatSingle: {
    width: "45%",
  },
  opponentSeatDouble: {
    width: "47.5%",
  },
  opponentSeatTriple: {
    width: "31.5%",
  },
  opponentSeatCompact: {
    height: 48,
    paddingVertical: 6,
    paddingLeft: 7,
    paddingRight: 4,
    borderRadius: 17,
    gap: 6,
  },
  activeSeat: {
    borderRadius: 18,
    borderColor: "#e8c66a",
    backgroundColor: "rgba(21,73,52,0.88)",
    shadowColor: "#c9a45c",
    shadowOpacity: 0.8,
    shadowRadius: 12,
    elevation: 10,
  },
  offlineSeat: {
    opacity: 0.42,
  },
  nowBadge: {
    position: "absolute",
    top: -10,
    right: 8,
    backgroundColor: "#c9a45c",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "#f5efe4",
    zIndex: 10,
  },
  nowBadgeText: {
    color: "#3b2417",
    fontSize: 10,
    fontWeight: "900",
  },
  playerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: "#d8c5a7",
    borderWidth: 2,
    borderColor: "#f5efe4",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  playerAvatarCompact: {
    width: 34,
    height: 34,
  },
  playerAvatarOffline: {
    backgroundColor: "#9ca3af",
  },
  playerAvatarText: {
    color: "#3b2417",
    fontSize: 19,
    fontWeight: "900",
  },
  playerAvatarTextCompact: {
    fontSize: 16,
  },
  opponentSeatMain: {
    flex: 1,
    minWidth: 0,
  },
  playerSeatName: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  playerSeatNameCompact: {
    fontSize: 11,
  },
  playerSeatCards: {
    color: "#d8c5a7",
    fontWeight: "800",
    fontSize: 11,
  },
  playerSeatCardsCompact: {
    fontSize: 9,
  },
  oneCardBadge: {
    position: "absolute",
    left: 10,
    bottom: -9,
    backgroundColor: "#ef4444",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "#ffffff",
    zIndex: 5,
  },
  oneCardBadgeText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  backCards: {
    position: "relative",
    width: 38,
    height: 46,
    marginLeft: 2,
  },
  backCardsCompact: {
    width: 31,
    height: 38,
  },
  smallBackCard: {
    position: "absolute",
    width: 28,
    height: 40,
    borderRadius: 7,
    backgroundColor: "#10251d",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  smallBackCardCompact: {
    width: 23,
    height: 32,
    borderRadius: 6,
  },
  smallBackCardTwo: {
    left: 5,
    top: 3,
  },
  smallBackCardThree: {
    left: 10,
    top: 6,
  },
  bottomPanel: {
    backgroundColor: "#f5efe4",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(216,197,167,0.7)",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: -6,
    },
    elevation: 18,
  },
  playerControlRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 7,
  },
  meAvatar: {
    width: 43,
    height: 43,
    borderRadius: 999,
    backgroundColor: "#c9a45c",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#17352a",
  },
  meAvatarText: {
    color: "#ffffff",
    fontSize: 19,
    fontWeight: "900",
  },
  meInfo: {
    flex: 1,
  },
  meName: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  meSub: {
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
  },
  actionButtons: {
    flexDirection: "row",
    gap: 6,
  },
  redrawButton: {
    backgroundColor: "#2d6f92",
    borderRadius: 13,
    minHeight: 38,
    minWidth: 62,
    paddingHorizontal: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#7dd3fc",
  },
  redrawButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  redrawButtonSub: {
    color: "#dff7ff",
    fontWeight: "900",
    fontSize: 9,
    marginTop: -1,
  },
  actionButton: {
    backgroundColor: "#c9a45c",
    borderRadius: 13,
    minHeight: 38,
    minWidth: 58,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#7a531c",
  },
  actionButtonReady: {
    backgroundColor: "#d9a93d",
    borderColor: "#8a5b13",
    shadowColor: "#c9a45c",
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 8,
  },
  actionButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  passButton: {
    backgroundColor: "#10251d",
    borderRadius: 13,
    minHeight: 38,
    minWidth: 52,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  passButtonReady: {
    backgroundColor: "#17352a",
    borderColor: "#8fc9a6",
    shadowColor: "#1f7a54",
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 7,
  },
  passButtonText: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 12,
  },
  handToolbar: {
    backgroundColor: "#ebe2d4",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  handToolbarRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  handTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 13,
  },
  handMeta: {
    color: "#1f7a54",
    fontWeight: "900",
    fontSize: 12,
  },
  turnCoach: {
    backgroundColor: "#f8f1e5",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e3d6c1",
  },
  turnCoachActive: {
    backgroundColor: "#edf8ef",
    borderColor: "#b9dec4",
  },
  turnCoachWarning: {
    backgroundColor: "#fff7ed",
    borderColor: "#fdba74",
  },
  turnCoachText: {
    color: "#536054",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
  },
  turnCoachTextWarning: {
    color: "#9a3412",
  },
  handArea: {
    backgroundColor: "#fbf8f1",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#ded1bb",
    overflow: "hidden",
  },
  handFanViewport: {
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 10,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  handFan: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "flex-start",
  },
  handCardButton: {
    borderRadius: 15,
    padding: 2,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 7,
  },
  draggingCard: {
    shadowOpacity: 0.36,
    shadowRadius: 16,
    elevation: 16,
  },
  playableCard: {
    backgroundColor: "#f0dfbb",
    borderWidth: 2,
    borderColor: "#1f7a54",
    shadowColor: "#047857",
    shadowOpacity: 0.24,
  },
  notPlayableCard: {
    opacity: 0.56,
    backgroundColor: "#e7ded0",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  playablePip: {
    position: "absolute",
    top: -7,
    right: -6,
    borderRadius: 999,
    backgroundColor: "#1f7a54",
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#f5efe4",
    zIndex: 10,
  },
  playablePipText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "900",
  },
});
