import { StyleSheet } from "react-native";
import { calmTheme } from "../theme";

export const gameStyles = StyleSheet.create({
  gameContainer: {
    flex: 1,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    paddingHorizontal: 10,
    paddingTop: 10,
    gap: 10,
  },
  gameContainerCompact: {
    paddingHorizontal: 6,
    paddingTop: 6,
    gap: 6,
  },
  gameTopBar: {
    minHeight: 58,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  gameTopBarCompact: {
    minHeight: 50,
    gap: 6,
  },
  gameInfoPill: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
    minWidth: 80,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 2,
  },
  gameInfoPillCompact: {
    minWidth: 68,
    borderRadius: 18,
    paddingVertical: 6,
    paddingHorizontal: 9,
    borderWidth: 2,
  },
  gameInfoLabel: {
    color: "#d8c5a7",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  gameInfoValue: {
    color: "#ffffff",
    fontSize: 19,
    fontWeight: "900",
  },
  turnBanner: {
    flex: 1,
    backgroundColor: calmTheme.colors.surface,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 1,
  },
  turnBannerCompact: {
    borderRadius: 18,
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderWidth: 2,
  },
  turnBannerActive: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.42)",
    shadowOpacity: 0.06,
  },
  turnBannerText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 14,
    textAlign: "center",
  },
  exitMiniButton: {
    backgroundColor: "rgba(216,93,93,0.10)",
    borderWidth: 1,
    borderColor: "rgba(216,93,93,0.24)",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  exitMiniButtonCompact: {
    borderRadius: 15,
    paddingHorizontal: 8,
    paddingVertical: 9,
    borderWidth: 2,
  },
  exitMiniText: {
    color: "#fecaca",
    fontWeight: "900",
    fontSize: 12,
  },
  gameConnectionBanner: {
    minHeight: 38,
    borderRadius: 16,
    backgroundColor: "#fff7ed",
    borderWidth: 1,
    borderColor: "#fdba74",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  gameConnectionText: {
    color: "#9a3412",
    fontSize: 12,
    fontWeight: "900",
  },
  tableWrapper: {
    flex: 1,
    minHeight: 250,
    borderRadius: 24,
  },
  tableWrapperCompact: {
    minHeight: 174,
    borderRadius: 22,
  },
  woodTable: {
    flex: 1,
    borderRadius: 24,
    padding: 6,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 6,
  },
  tableShadow: {
    flex: 1,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.16)",
    padding: 3,
  },
  greenTable: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    position: "relative",
    overflow: "hidden",
    padding: 11,
    justifyContent: "space-between",
    gap: 10,
  },
  tableGlow: {
    position: "absolute",
    left: 34,
    right: 34,
    top: 72,
    bottom: 68,
    borderRadius: 999,
    backgroundColor: "rgba(245,239,228,0.04)",
  },
  tableInnerLine: {
    position: "absolute",
    left: 12,
    right: 12,
    top: 12,
    bottom: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.06)",
  },
  opponentRail: {
    flexDirection: "row",
    gap: 8,
    minHeight: 62,
    alignItems: "flex-start",
    justifyContent: "center",
    zIndex: 3,
  },
  opponentRailCompact: {
    minHeight: 50,
    gap: 6,
  },
  tableCenterZone: {
    flex: 1,
    minHeight: 142,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    zIndex: 2,
  },
  tableCenterZoneCompact: {
    minHeight: 104,
    paddingVertical: 0,
  },
  pileStage: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 22,
    backgroundColor: "rgba(2,8,6,0.34)",
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    shadowColor: "#000",
    shadowOpacity: 0.10,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 7,
    },
  },
  pileStageActive: {
    borderColor: "#86efac",
    backgroundColor: "rgba(22,101,52,0.28)",
  },
  pileStageCompact: {
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 23,
  },
  tableDropHint: {
    position: "absolute",
    top: -15,
    alignSelf: "center",
    backgroundColor: "#dcfce7",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#86efac",
    zIndex: 20,
  },
  tableDropHintText: {
    color: "#166534",
    fontSize: 10,
    fontWeight: "900",
  },
  pileSlot: {
    alignItems: "center",
    gap: 7,
  },
  pileDivider: {
    width: 1,
    height: 92,
    backgroundColor: "rgba(245,239,228,0.16)",
  },
  pileDividerCompact: {
    height: 74,
  },
  pileCaption: {
    color: "rgba(245,239,228,0.74)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  deckCard: {
    width: 78,
    height: 112,
    borderRadius: 16,
    backgroundColor: calmTheme.colors.surfaceDark,
    borderWidth: 1,
    borderColor: "rgba(247,243,236,0.20)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 6,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 3,
  },
  deckCardReady: {
    borderColor: calmTheme.colors.accent,
    shadowOpacity: 0.12,
  },
  deckCardCompact: {
    width: 64,
    height: 92,
    borderRadius: 15,
  },
  disabledDeck: {
    opacity: 0.55,
  },
  deckBackImage: {
    position: "absolute",
    width: 78,
    height: 112,
    borderRadius: 16,
    opacity: 0.9,
  },
  deckBackImageCompact: {
    width: 64,
    height: 92,
    borderRadius: 13,
  },
  deckLabel: {
    color: "#fff7ed",
    fontWeight: "900",
    marginTop: 9,
    fontSize: 12,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffset: {
      width: 0,
      height: 1,
    },
    textShadowRadius: 3,
  },
  discardCard: {
    width: 86,
    height: 122,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    shadowColor: "#000",
    shadowOpacity: 0.34,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 8,
  },
  discardCardCompact: {
    width: 72,
    height: 102,
  },
  tableCardImage: {
    width: 86,
    height: 122,
  },
  tableCardImageCompact: {
    width: 72,
    height: 102,
  },
  tableHud: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    zIndex: 3,
    backgroundColor: "rgba(2,8,6,0.42)",
    borderRadius: 18,
    padding: 4,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  tableHudPill: {
    backgroundColor: "rgba(247,243,236,0.92)",
    borderRadius: 999,
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.10)",
  },
  directionText: {
    fontSize: 12,
    fontWeight: "900",
    color: "#17352a",
    textTransform: "uppercase",
  },
  tableHudStatus: {
    flex: 1,
    backgroundColor: "rgba(247,243,236,0.92)",
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.10)",
    alignItems: "center",
  },
  statusInfoText: {
    color: "#374151",
    fontWeight: "900",
    fontSize: 11,
  },
  penaltyBubble: {
    backgroundColor: calmTheme.colors.danger,
    borderRadius: 999,
    minWidth: 44,
    height: 42,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  penaltyBubbleText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
  },
  winRibbon: {
    position: "absolute",
    left: -30,
    right: -30,
    top: "45%",
    backgroundColor: "rgba(245,239,228,0.96)",
    paddingVertical: 16,
    transform: [{ rotate: "-10deg" }],
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  winRibbonText: {
    textAlign: "center",
    color: "#17352a",
    fontSize: 20,
    fontWeight: "900",
  },
  opponentSeat: {
    flexGrow: 0,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: 164,
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(7,28,24,0.86)",
    borderRadius: 20,
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 6,
    borderWidth: 2,
    borderColor: "rgba(245,239,228,0.42)",
    position: "relative",
  },
  opponentSeatSingle: {
    width: "45%",
  },
  opponentSeatDouble: {
    width: "47.5%",
  },
  opponentSeatTriple: {
    width: "30%",
  },
  opponentSeatCompact: {
    height: 48,
    paddingVertical: 6,
    paddingLeft: 7,
    paddingRight: 4,
    borderRadius: 17,
    gap: 6,
  },
  activeSeat: {
    borderRadius: 18,
    borderColor: "#f8d469",
    backgroundColor: "rgba(18,59,45,0.96)",
    shadowColor: "#f8d469",
    shadowOpacity: 0.8,
    shadowRadius: 18,
    elevation: 10,
    transform: [{ translateY: -2 }],
  },
  offlineSeat: {
    opacity: 0.42,
  },
  finishedSeat: {
    opacity: 0.72,
    borderColor: "#c9a45c",
    backgroundColor: "rgba(56,39,20,0.82)",
  },
  nowBadge: {
    position: "absolute",
    top: -10,
    right: 8,
    backgroundColor: "#f4b739",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "#f5efe4",
    zIndex: 10,
  },
  nowBadgeText: {
    color: "#3b2417",
    fontSize: 10,
    fontWeight: "900",
  },
  spectatorBadge: {
    position: "absolute",
    left: 8,
    bottom: -9,
    backgroundColor: "#2d6f92",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "#d9f7e8",
    zIndex: 10,
  },
  spectatorBadgeText: {
    color: "#ffffff",
    fontSize: 9,
    fontWeight: "900",
  },
  playerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: "#d8c5a7",
    borderWidth: 2,
    borderColor: "#f5efe4",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  playerAvatarCompact: {
    width: 34,
    height: 34,
  },
  playerAvatarOffline: {
    backgroundColor: "#9ca3af",
  },
  playerAvatarText: {
    color: "#3b2417",
    fontSize: 19,
    fontWeight: "900",
  },
  playerAvatarTextCompact: {
    fontSize: 16,
  },
  opponentSeatMain: {
    flex: 1,
    minWidth: 0,
  },
  playerSeatName: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  playerSeatNameCompact: {
    fontSize: 11,
  },
  playerSeatCards: {
    color: "#d8c5a7",
    fontWeight: "800",
    fontSize: 11,
  },
  playerSeatCardsCompact: {
    fontSize: 9,
  },
  oneCardBadge: {
    position: "absolute",
    left: 10,
    bottom: -9,
    backgroundColor: "#ef4444",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "#ffffff",
    zIndex: 5,
  },
  oneCardBadgeText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  backCards: {
    position: "relative",
    width: 38,
    height: 46,
    marginLeft: 2,
  },
  backCardsCompact: {
    width: 31,
    height: 38,
  },
  smallBackCard: {
    position: "absolute",
    width: 28,
    height: 40,
    borderRadius: 7,
    backgroundColor: "#10251d",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  smallBackCardCompact: {
    width: 23,
    height: 32,
    borderRadius: 6,
  },
  smallBackCardTwo: {
    left: 5,
    top: 3,
  },
  smallBackCardThree: {
    left: 10,
    top: 6,
  },
  bottomPanel: {
    backgroundColor: calmTheme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    padding: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: -6,
    },
    elevation: 8,
  },
  bottomPanelCompact: {
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    padding: 8,
    borderWidth: 3,
  },
  playerControlRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 7,
  },
  playerControlRowCompact: {
    flexWrap: "wrap",
    gap: 7,
    marginBottom: 5,
  },
  meAvatar: {
    width: 43,
    height: 43,
    borderRadius: 999,
    backgroundColor: calmTheme.colors.accent,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(16,32,29,0.34)",
    shadowOpacity: 0.10,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 7,
  },
  meAvatarText: {
    color: "#ffffff",
    fontSize: 19,
    fontWeight: "900",
  },
  meInfo: {
    flex: 1,
  },
  meInfoCompact: {
    minWidth: 0,
  },
  meName: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  meSub: {
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
  },
  actionButtons: {
    flexDirection: "row",
    gap: 6,
  },
  actionButtonsCompact: {
    width: "100%",
    gap: 7,
  },
  redrawButton: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 12,
    minHeight: 38,
    minWidth: 62,
    paddingHorizontal: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  redrawButtonCompact: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
  },
  redrawButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  redrawButtonSub: {
    color: "#dff7ff",
    fontWeight: "900",
    fontSize: 9,
    marginTop: -1,
  },
  playSelectedButton: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 12,
    minHeight: 38,
    minWidth: 64,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(16,32,29,0.24)",
  },
  playSelectedButtonCompact: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
  },
  playSelectedButtonReady: {
    backgroundColor: "#10251d",
    borderColor: calmTheme.colors.accent,
    shadowColor: calmTheme.colors.accent,
    shadowOpacity: 0.14,
    shadowRadius: 7,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 8,
  },
  playSelectedButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  playSelectedButtonSub: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 9,
    marginTop: -1,
    maxWidth: 68,
  },
  actionButton: {
    backgroundColor: calmTheme.colors.accent,
    borderRadius: 12,
    minHeight: 38,
    minWidth: 58,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  actionButtonCompact: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
  },
  actionButtonReady: {
    backgroundColor: calmTheme.colors.accent,
    shadowOpacity: 0.10,
    shadowRadius: 6,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 8,
  },
  actionButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  passButton: {
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 12,
    minHeight: 38,
    minWidth: 52,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  passButtonCompact: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
  },
  passButtonReady: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.44)",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 7,
  },
  passButtonText: {
    color: calmTheme.colors.text,
    fontWeight: "900",
    fontSize: 12,
  },
  handToolbar: {
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  handToolbarCompact: {
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 5,
  },
  handToolbarRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    flexShrink: 1,
  },
  handTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 13,
    flexShrink: 0,
  },
  handMeta: {
    color: "#1f7a54",
    fontWeight: "900",
    fontSize: 12,
    flexShrink: 1,
    minWidth: 0,
  },
  handSortSegment: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.48)",
    borderRadius: 14,
    padding: 2,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  handSortButton: {
    minHeight: 28,
    borderRadius: 13,
    paddingHorizontal: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  handSortButtonActive: {
    backgroundColor: calmTheme.colors.surfaceDark,
  },
  handSortButtonText: {
    color: "#6b512b",
    fontWeight: "900",
    fontSize: 10,
  },
  handSortButtonTextActive: {
    color: "#ffffff",
  },
  turnCoach: {
    backgroundColor: "rgba(16,32,29,0.04)",
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e3d6c1",
  },
  turnCoachCompact: {
    borderRadius: 14,
    paddingVertical: 7,
    paddingHorizontal: 10,
    marginBottom: 5,
  },
  turnCoachActive: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.34)",
  },
  turnCoachWarning: {
    backgroundColor: "#fff7ed",
    borderColor: "#fdba74",
  },
  turnCoachText: {
    color: "#536054",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
  },
  turnCoachTextWarning: {
    color: "#9a3412",
  },
  ruleBannerList: {
    gap: 6,
    marginBottom: 8,
  },
  ruleBanner: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: "rgba(16,32,29,0.04)",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    paddingVertical: 7,
    paddingHorizontal: 11,
    justifyContent: "center",
  },
  ruleBannerDanger: {
    backgroundColor: "rgba(216,93,93,0.11)",
    borderColor: "rgba(216,93,93,0.24)",
  },
  ruleBannerSuccess: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.34)",
  },
  ruleBannerWarning: {
    backgroundColor: calmTheme.colors.accentSoft,
    borderColor: "rgba(210,168,78,0.30)",
  },
  ruleBannerLabel: {
    color: "#6d614f",
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  ruleBannerText: {
    color: "#10251d",
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 16,
    marginTop: 1,
  },
  ruleStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  ruleStatusChip: {
    flex: 1,
    minWidth: 92,
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: "rgba(16,32,29,0.04)",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    paddingVertical: 6,
    paddingHorizontal: 9,
    justifyContent: "center",
  },
  ruleStatusChipDanger: {
    backgroundColor: "rgba(216,93,93,0.12)",
    borderColor: "rgba(216,93,93,0.24)",
  },
  ruleStatusChipSuccess: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.34)",
  },
  ruleStatusChipWarning: {
    backgroundColor: calmTheme.colors.accentSoft,
    borderColor: calmTheme.colors.border,
  },
  ruleStatusLabel: {
    color: "#6d614f",
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  ruleStatusValue: {
    color: "#10251d",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 1,
  },
  handArea: {
    backgroundColor: "#fbf8f1",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    overflow: "hidden",
  },
  handAreaCompact: {
    borderRadius: 22,
    borderWidth: 2,
  },
  waitingHandCard: {
    minHeight: 150,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    gap: 7,
  },
  waitingHandTitle: {
    color: "#10251d",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
  },
  waitingHandText: {
    color: "#6d614f",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 18,
  },
  handFanViewport: {
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 10,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  handFanViewportCompact: {
    paddingHorizontal: 8,
    paddingTop: 14,
    paddingBottom: 6,
  },
  handFan: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "flex-start",
  },
  handCardButton: {
    borderRadius: 15,
    padding: 2,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 7,
  },
  draggingCard: {
    shadowOpacity: 0.36,
    shadowRadius: 16,
    elevation: 16,
  },
  playableCard: {
    backgroundColor: calmTheme.colors.accentSoft,
    borderWidth: 1,
    borderColor: "rgba(210,168,78,0.58)",
    shadowOpacity: 0.12,
  },
  selectedCard: {
    backgroundColor: "#fff7dd",
    borderColor: "#10251d",
    shadowColor: calmTheme.colors.accent,
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 12,
  },
  notPlayableCard: {
    opacity: 0.52,
    backgroundColor: "#e7ded0",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  playablePip: {
    position: "absolute",
    top: -7,
    right: -6,
    borderRadius: 999,
    backgroundColor: "#d6a53a",
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#f5efe4",
    zIndex: 10,
  },
  playablePipText: {
    color: "#17352a",
    fontSize: 11,
    fontWeight: "900",
  },
  playablePipTextSelected: {
    color: "#ffffff",
    fontSize: 9,
  },
  playablePipSelected: {
    width: 34,
    backgroundColor: "#10251d",
    borderColor: calmTheme.colors.accent,
  },
  winnerHero: {
    backgroundColor: "#10251d",
    borderRadius: 22,
    padding: 18,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  winnerHeroEyebrow: {
    color: "#d8c5a7",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  winnerHeroTitle: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "900",
    marginTop: 3,
  },
  winnerHeroText: {
    color: "#d9e8df",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 4,
    textAlign: "center",
  },
  finishRewardGrid: {
    flexDirection: "row",
    gap: 10,
  },
  finishRewardTile: {
    flex: 1,
    minHeight: 58,
    borderRadius: 16,
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#ded1bb",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  finishRewardLabel: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  finishRewardValue: {
    color: "#10251d",
    fontSize: 20,
    fontWeight: "900",
    marginTop: 2,
  },
  finishMissionText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  rankingList: {
    gap: 7,
  },
  rankingRow: {
    minHeight: 44,
    borderRadius: 15,
    backgroundColor: "#fffaf0",
    borderWidth: 1,
    borderColor: "#ded1bb",
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 10,
  },
  rankingRowLoser: {
    backgroundColor: "#fee2e2",
    borderColor: "#fca5a5",
  },
  rankingPlace: {
    width: 54,
    color: "#8c6b33",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  rankingName: {
    flex: 1,
    color: "#10251d",
    fontSize: 14,
    fontWeight: "900",
  },
  rankingMeta: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  rematchPanel: {
    backgroundColor: "#ebe2d4",
    borderRadius: 18,
    padding: 12,
    gap: 7,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  rematchTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  rematchVoteRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  rematchVoteName: {
    color: "#3b2f22",
    fontSize: 12,
    fontWeight: "900",
  },
  rematchVoteState: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  rematchVoteStateReady: {
    color: "#1f7a54",
  },
});
