import { StyleSheet } from "react-native";
import { calmTheme } from "../theme";

export const lobbyStyles = StyleSheet.create({
  homeShell: {
    flex: 1,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
    position: "relative",
  },
  homeScroll: {
    flexGrow: 1,
    justifyContent: "flex-start",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 150,
  },
  homeScrollCompact: {
    paddingBottom: 150,
  },
  homeCard: {
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
    backgroundColor: "rgba(4,19,16,0.18)",
    borderRadius: 0,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 0,
    gap: 8,
    borderWidth: 0,
    borderColor: "transparent",
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 0,
  },
  homeBottomNavWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
    paddingHorizontal: 12,
  },
  homeCardCompact: {
    paddingHorizontal: 10,
    paddingTop: 7,
    gap: 7,
  },
  gameHomeGlowGold: {
    position: "absolute",
    top: -112,
    right: -84,
    width: 250,
    height: 250,
    borderRadius: 999,
    backgroundColor: "rgba(255,205,88,0.20)",
  },
  gameHomeGlowGreen: {
    position: "absolute",
    bottom: 34,
    left: -96,
    width: 280,
    height: 280,
    borderRadius: 999,
    backgroundColor: "rgba(48,219,125,0.13)",
  },
  homeBody: {
    width: "100%",
    minHeight: 0,
  },
  tabPage: {
    width: "100%",
    gap: 8,
    justifyContent: "flex-start",
  },
  tabPageCompact: {
    gap: 7,
  },
  homeSection: {
    gap: 9,
    padding: 12,
  },
  homeSectionCompact: {
    gap: 8,
    padding: 10,
  },
  tabScroll: {
    flex: 1,
    minHeight: 0,
  },
  tabScrollContent: {
    gap: 12,
    paddingBottom: 10,
  },
  tabHeroCard: {
    gap: 12,
    padding: 16,
  },
  tabSectionCard: {
    gap: 12,
    padding: 14,
  },
  profileSettingsCard: {
    gap: 12,
  },
  appTabHeader: {
    backgroundColor: "#123b2d",
    borderRadius: 24,
    padding: 13,
    borderWidth: 3,
    borderColor: "#f1c75b",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 10,
  },
  marketTabHeader: {
    backgroundColor: "#7a4a20",
    borderColor: "#d6a348",
  },
  socialTabHeader: {
    backgroundColor: "#4b2ca1",
    borderColor: "#a891ff",
  },
  rulesTabHeader: {
    backgroundColor: "#183a57",
    borderColor: "#8bd2ff",
  },
  profileTabHeader: {
    backgroundColor: "#243326",
    borderColor: "#c9a45c",
  },
  marketSign: {
    minHeight: 78,
    borderRadius: 18,
    backgroundColor: "#a8662d",
    borderWidth: 3,
    borderColor: "#5c3315",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    elevation: 10,
  },
  marketSignTitle: {
    color: "#3b210f",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: 0,
    textShadowColor: "rgba(255,236,176,0.45)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  marketSignBolt: {
    width: 28,
    height: 42,
    borderRadius: 7,
    backgroundColor: "#c8c8c8",
    borderWidth: 2,
    borderColor: "#636363",
  },
  dailyDealsRibbon: {
    backgroundColor: "#d8f3ff",
    borderRadius: 16,
    borderWidth: 3,
    borderColor: "#6e9fb5",
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: "center",
  },
  dailyDealsTitle: {
    color: "#0e2942",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 0,
    textShadowColor: "rgba(255,255,255,0.8)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  dailyDealsText: {
    color: "#24455e",
    fontSize: 11,
    fontWeight: "900",
    marginTop: 2,
  },
  socialActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  socialActionTile: {
    flex: 1,
    flexBasis: "30%",
    minWidth: 0,
    minHeight: 52,
    borderRadius: 13,
    backgroundColor: "rgba(16,32,29,0.06)",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  socialActionIcon: {
    color: calmTheme.colors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  socialActionText: {
    color: calmTheme.colors.textMuted,
    fontSize: 10,
    fontWeight: "800",
    maxWidth: "100%",
  },
  appTabEyebrow: {
    color: "#f8d469",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  appTabTitle: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 0,
    marginTop: 2,
  },
  appTabText: {
    color: "#d8c5a7",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
    marginTop: 4,
  },
  gameHomeTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minHeight: 52,
  },
  gamePlayerButton: {
    flex: 1,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 2,
  },
  gamePlayerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    shadowOpacity: 0.35,
    shadowRadius: 9,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 8,
  },
  gamePlayerAvatarText: {
    fontSize: 17,
    fontWeight: "900",
  },
  gamePlayerCopy: {
    flex: 1,
    minWidth: 0,
  },
  gamePlayerName: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  gamePlayerMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginTop: 4,
  },
  gamePlayerLevel: {
    color: "#f8d469",
    fontSize: 11,
    fontWeight: "900",
  },
  gamePlayerXpTrack: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
    overflow: "hidden",
  },
  gamePlayerXpFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#38d97f",
  },
  gameResourceStack: {
    gap: 5,
    minWidth: 96,
  },
  gameCurrencyPill: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 10,
    paddingVertical: 4,
    paddingLeft: 8,
    paddingRight: 4,
    borderWidth: 1,
    borderColor: "rgba(210,168,78,0.42)",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    elevation: 1,
  },
  gameCurrencyPillGem: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderColor: "rgba(111,174,148,0.48)",
  },
  gameCurrencyIcon: {
    width: 18,
    height: 18,
  },
  gameCurrencyValue: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    minWidth: 26,
    textAlign: "right",
  },
  gameCurrencyPlus: {
    width: 19,
    height: 19,
    borderRadius: 999,
    backgroundColor: "rgba(247,243,236,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(247,243,236,0.18)",
  },
  gameCurrencyPlusText: {
    color: "#ffffff",
    fontSize: 15,
    lineHeight: 17,
    fontWeight: "900",
  },
  gameBrandRow: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 4,
  },
  gameBrandRowCompact: {
    minHeight: 36,
    paddingHorizontal: 2,
  },
  gameBrandEyebrow: {
    color: "#f8d469",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.7,
    textTransform: "uppercase",
  },
  gameBrandTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 0,
    textShadowColor: "rgba(0,0,0,0.34)",
    textShadowOffset: {
      width: 0,
      height: 3,
    },
    textShadowRadius: 0,
  },
  gameBrandTitleCompact: {
    fontSize: 22,
  },
  gameOnlinePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "#fff4d8",
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 9,
    borderWidth: 1,
    borderColor: "rgba(255,208,87,0.78)",
  },
  gameOnlineText: {
    color: "#082118",
    fontSize: 11,
    fontWeight: "900",
  },
  gameSeasonStrip: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(12,31,45,0.68)",
    borderRadius: 16,
    padding: 8,
    borderWidth: 1,
    borderColor: "rgba(255,208,87,0.25)",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 4,
  },
  gameSeasonShield: {
    width: 39,
    height: 39,
    borderRadius: 14,
    backgroundColor: "#f4b739",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff2a8",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 7,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 7,
  },
  gameSeasonShieldText: {
    color: "#4a2f0d",
    fontSize: 17,
    fontWeight: "900",
  },
  gameSeasonCopy: {
    flex: 1,
    minWidth: 0,
  },
  gameSeasonTitle: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  gameSeasonText: {
    color: "#d8c5a7",
    fontSize: 9,
    fontWeight: "800",
    marginTop: 2,
  },
  gameSeasonButton: {
    minHeight: 32,
    borderRadius: 999,
    backgroundColor: "#123b2d",
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#50e78c",
  },
  gameSeasonButtonText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  gameModeGrid: {
    gap: 7,
  },
  gameModeMiniCard: {
    width: "100%",
    minWidth: 0,
    minHeight: 54,
    backgroundColor: "rgba(246,239,225,0.96)",
    borderRadius: 13,
    padding: 9,
    paddingRight: 62,
    borderWidth: 1,
    borderColor: "rgba(216,197,167,0.76)",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    justifyContent: "flex-start",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 2,
  },
  gameModeMiniCardActive: {
    backgroundColor: "#123b2d",
    borderColor: "#50e78c",
  },
  gameModeMiniIcon: {
    width: 26,
    height: 26,
    borderRadius: 10,
    backgroundColor: "#17352a",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.58)",
  },
  gameModeMiniIconBlue: {
    backgroundColor: "#183a57",
    borderColor: "rgba(139,210,255,0.68)",
  },
  gameModeMiniIconPurple: {
    backgroundColor: "#49317f",
    borderColor: "rgba(216,180,254,0.68)",
  },
  gameModeMiniIconText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.28)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  gameModeMiniCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  gameModeMiniTitle: {
    color: "#10251d",
    fontSize: 11,
    fontWeight: "900",
  },
  gameModeMiniText: {
    color: "#6d614f",
    fontSize: 9,
    fontWeight: "800",
  },
  gameModeMiniBadge: {
    position: "absolute",
    top: 9,
    right: 9,
    backgroundColor: calmTheme.colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
    zIndex: 3,
  },
  gameModeMiniBadgeRed: {
    position: "absolute",
    top: 9,
    right: 9,
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    backgroundColor: calmTheme.colors.accentSoft,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(210,168,78,0.38)",
    zIndex: 3,
  },
  gameModeMiniBadgeText: {
    color: calmTheme.colors.text,
    fontSize: 9,
    fontWeight: "900",
  },
  gameModeHero: {
    minHeight: 206,
    borderRadius: 20,
    padding: 12,
    gap: 8,
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "rgba(255,208,87,0.48)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 9,
    },
    elevation: 8,
  },
  gameModeHeroCompact: {
    minHeight: 190,
    borderRadius: 18,
    padding: 10,
    gap: 7,
  },
  gameModeHeroGlow: {
    position: "absolute",
    top: -74,
    right: -42,
    width: 190,
    height: 190,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.13)",
  },
  gameModeHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  gameModeHeaderCompact: {
    gap: 7,
  },
  gameModeBadge: {
    backgroundColor: "#f8d469",
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 9,
    borderWidth: 1,
    borderColor: "#5c3c18",
  },
  gameModeBadgeText: {
    color: "#20130a",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  gameEntryBadge: {
    minWidth: 58,
    backgroundColor: "rgba(6,20,15,0.72)",
    borderRadius: 15,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    alignItems: "center",
  },
  gameEntryLabel: {
    color: "#d8c5a7",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  gameEntryValue: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  gameModeBody: {
    flex: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
  },
  gameModeBodyCompact: {
    gap: 8,
  },
  gameModeCopy: {
    flex: 1,
    minWidth: 0,
    gap: 6,
    alignItems: "flex-start",
  },
  gameModeTitle: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 0,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffset: {
      width: 0,
      height: 3,
    },
    textShadowRadius: 0,
  },
  gameModeTitleCompact: {
    fontSize: 20,
  },
  gameModeText: {
    color: "#e7f3ec",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    maxWidth: 210,
    textAlign: "left",
  },
  gameModeTextCompact: {
    fontSize: 10,
    lineHeight: 14,
    maxWidth: 190,
  },
  gameArenaStage: {
    width: 112,
    minHeight: 68,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  gameArenaStageCompact: {
    width: 98,
    minHeight: 62,
  },
  gameArenaGlow: {
    position: "absolute",
    width: 230,
    height: 112,
    borderRadius: 999,
    backgroundColor: "rgba(255,244,216,0.14)",
  },
  gameArenaPlate: {
    width: 108,
    height: 64,
    borderRadius: 22,
    borderWidth: 2,
    backgroundColor: "rgba(7,30,22,0.32)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 6,
  },
  gameArenaPlateCompact: {
    width: 94,
    height: 58,
    borderRadius: 20,
  },
  gameArenaInnerGlow: {
    position: "absolute",
    width: 170,
    height: 78,
    borderRadius: 999,
    backgroundColor: "rgba(80,231,140,0.14)",
  },
  gameTableSkinPreview: {
    position: "absolute",
    width: 78,
    height: 46,
    borderRadius: 18,
    borderWidth: 2,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-7deg" }],
  },
  gameTableSkinPreviewCompact: {
    width: 70,
    height: 40,
    borderRadius: 16,
  },
  gameTableSkinRail: {
    position: "absolute",
    width: 68,
    height: 34,
    borderRadius: 15,
    borderWidth: 2,
  },
  gameTableSkinRailCompact: {
    width: 60,
    height: 30,
    borderRadius: 14,
  },
  gameTableSkinFelt: {
    width: 46,
    height: 22,
    borderRadius: 12,
    borderWidth: 1,
  },
  gameTableSkinFeltCompact: {
    width: 40,
    height: 19,
    borderRadius: 10,
  },
  gameDeckStack: {
    position: "absolute",
    right: 8,
    top: 8,
    width: 36,
    height: 48,
  },
  gameDeckStackLeft: {
    left: 8,
    right: undefined,
    transform: [{ rotate: "-13deg" }],
    opacity: 0.8,
  },
  gameDeckPreview: {
    position: "absolute",
    right: 0,
    top: 6,
    width: 24,
    height: 34,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#f6efe1",
    transform: [{ rotate: "8deg" }],
  },
  gameDeckPreviewBack: {
    right: 8,
    top: 0,
    opacity: 0.86,
    transform: [{ rotate: "-8deg" }],
  },
  gameDeckPreviewCompact: {
    width: 22,
    height: 31,
    borderRadius: 6,
  },
  gameStartButton: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: "#f4b739",
    borderWidth: 1,
    borderColor: "#7c4f12",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 7,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 6,
  },
  gameStartButtonCompact: {
    minHeight: 52,
    borderRadius: 15,
  },
  gameStartButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
    textShadowColor: "rgba(91,50,12,0.65)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  gameStartButtonSub: {
    color: "#5c3c18",
    fontSize: 9,
    fontWeight: "900",
    marginTop: 1,
    textTransform: "uppercase",
  },
  gameRewardGrid: {
    flexDirection: "row",
    gap: 8,
  },
  gameRewardGridCompact: {
    flexDirection: "column",
    gap: 7,
  },
  gameRewardTile: {
    flex: 1,
    minHeight: 58,
    backgroundColor: "rgba(18,59,45,0.82)",
    borderRadius: 16,
    padding: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: "rgba(80,231,140,0.46)",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 2,
  },
  gameRewardTileMuted: {
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  gameRewardIcon: {
    width: 28,
    height: 28,
  },
  gameRewardCopy: {
    flex: 1,
    minWidth: 0,
  },
  gameRewardTitle: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  gameRewardText: {
    color: "#d9e8df",
    fontSize: 9,
    fontWeight: "800",
    marginTop: 2,
  },
  gameNoticeDot: {
    position: "absolute",
    top: -7,
    right: -5,
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: "#ef2d2d",
    borderWidth: 2,
    borderColor: "#fff6dc",
    alignItems: "center",
    justifyContent: "center",
  },
  gameNoticeDotText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 11,
  },
  gameMissionTile: {
    flex: 1,
    minHeight: 58,
    backgroundColor: "#f6efe1",
    borderRadius: 16,
    padding: 9,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(244,183,57,0.58)",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 2,
  },
  gameMissionTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  gameMissionTitle: {
    flex: 1,
    color: "#10251d",
    fontSize: 11,
    fontWeight: "900",
  },
  gameMissionCount: {
    color: "#0f7a4d",
    fontSize: 11,
    fontWeight: "900",
  },
  gameMissionTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: "#ded1bb",
    overflow: "hidden",
    marginTop: 6,
  },
  gameMissionFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#0f7a4d",
  },
  gameMissionReward: {
    color: "#8c6b33",
    fontSize: 9,
    fontWeight: "900",
    marginTop: 4,
    textTransform: "uppercase",
  },
  gameJoinPanel: {
    backgroundColor: "#f6efe1",
    borderRadius: 16,
    padding: 10,
    gap: 7,
    borderWidth: 1,
    borderColor: "#d8c5a7",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 2,
  },
  gameJoinPanelCompact: {
    borderRadius: 15,
    padding: 9,
  },
  gameJoinHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  gameJoinEyebrow: {
    color: "#8c6b33",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  gameJoinTitle: {
    color: "#10251d",
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0,
  },
  gameJoinHint: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "900",
  },
  gameJoinInlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  gameCodeInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 46,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d8c5a7",
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontSize: 17,
    color: "#111827",
    fontWeight: "900",
    letterSpacing: 3,
    textAlign: "center",
  },
  gameCodeInputCompact: {
    minHeight: 44,
    paddingHorizontal: 8,
    fontSize: 16,
    letterSpacing: 2,
  },
  gameJoinButton: {
    flexShrink: 0,
    minHeight: 46,
    minWidth: 82,
    borderRadius: 14,
    backgroundColor: "#17352a",
    borderWidth: 1,
    borderColor: "#8fc9a6",
    alignItems: "center",
    justifyContent: "center",
  },
  gameJoinButtonCompact: {
    minHeight: 44,
    minWidth: 74,
  },
  gameJoinButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.35)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  gameBottomNav: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 6,
    backgroundColor: "rgba(246,239,225,0.96)",
    borderRadius: 0,
    marginHorizontal: -12,
    marginBottom: 0,
    paddingHorizontal: 10,
    paddingTop: 9,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderColor: "rgba(216,197,167,0.95)",
  },
  gameBottomNavItem: {
    flex: 1,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "transparent",
  },
  gameBottomNavItemActive: {
    backgroundColor: "#17352a",
    borderColor: "#c9a45c",
  },
  gameBottomNavIcon: {
    color: "#6d614f",
    fontSize: 18,
    fontWeight: "900",
  },
  gameBottomNavIconActive: {
    color: "#ffffff",
  },
  gameBottomNavText: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "900",
  },
  gameBottomNavTextActive: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  gameNavBadge: {
    position: "absolute",
    top: 7,
    right: 11,
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: "#ef2d2d",
    borderWidth: 2,
    borderColor: "#fff6dc",
  },
  gameNavBadgeTiny: {
    position: "absolute",
    top: 7,
    right: 10,
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#ef2d2d",
    borderWidth: 2,
    borderColor: "#fff6dc",
  },
  gameFeatureModalCard: {
    maxWidth: 430,
    backgroundColor: "#071c18",
    borderWidth: 3,
    borderColor: "#f1c75b",
  },
  featureModalHero: {
    flexDirection: "row",
    gap: 13,
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.09)",
    borderRadius: 24,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,208,87,0.34)",
  },
  featureModalIcon: {
    width: 70,
    height: 70,
    borderRadius: 24,
    backgroundColor: "#2584ff",
    borderWidth: 3,
    borderColor: "#9bd0ff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 8,
  },
  featureModalIconText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
  },
  featureModalCopy: {
    flex: 1,
    gap: 3,
  },
  featureModalEyebrow: {
    color: "#f8d469",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  featureModalTitle: {
    color: "#ffffff",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 0,
  },
  featureModalText: {
    color: "#d8c5a7",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  featureRoadmapList: {
    gap: 8,
  },
  matchmakingStatusCard: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  matchmakingPulse: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: calmTheme.colors.secondary,
    borderWidth: 0,
  },
  matchmakingStatusCopy: {
    flex: 1,
  },
  matchmakingStatusTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  matchmakingStatusText: {
    color: calmTheme.colors.textOnDarkMuted,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  matchmakingWaitText: {
    color: calmTheme.colors.accentStrong,
    fontSize: 13,
    fontWeight: "900",
  },
  featureRoadmapItem: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#f6efe1",
    borderRadius: 17,
    padding: 9,
    borderWidth: 1,
    borderColor: "#d6b35c",
  },
  featureRoadmapNumber: {
    width: 30,
    height: 30,
    borderRadius: 11,
    overflow: "hidden",
    backgroundColor: "#f4b739",
    color: "#4a2f0d",
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 15,
    fontWeight: "900",
  },
  featureRoadmapText: {
    color: "#10251d",
    fontSize: 14,
    fontWeight: "900",
  },
  friendPreviewList: {
    gap: 8,
  },
  publicRoomPreviewList: {
    gap: 10,
    padding: 14,
  },
  publicRoomPreviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  publicRoomPreviewTitle: {
    color: calmTheme.colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  publicRoomPreviewMeta: {
    color: calmTheme.colors.textMuted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  publicRoomPreviewRow: {
    minHeight: 58,
    borderRadius: 14,
    backgroundColor: "rgba(16,32,29,0.04)",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 9,
  },
  publicRoomIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: calmTheme.colors.surfaceDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  publicRoomIconText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  socialProfileCard: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 15,
    padding: 11,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  socialProfileLevel: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: calmTheme.colors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  socialProfileLevelText: {
    color: "#4a2f0d",
    fontSize: 12,
    fontWeight: "900",
  },
  socialProfileCopy: {
    flex: 1,
  },
  socialProfileName: {
    color: calmTheme.colors.textOnDark,
    fontSize: 16,
    fontWeight: "900",
  },
  socialProfileText: {
    color: calmTheme.colors.textOnDarkMuted,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  friendPreviewRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(16,32,29,0.04)",
    borderRadius: 14,
    padding: 9,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  friendPreviewAvatar: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: calmTheme.colors.surfaceDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  friendPreviewAvatarText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  friendPreviewCopy: {
    flex: 1,
  },
  friendPreviewName: {
    color: "#10251d",
    fontSize: 14,
    fontWeight: "900",
  },
  friendPreviewStatus: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 2,
  },
  friendPreviewButton: {
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  friendPreviewButtonText: {
    color: calmTheme.colors.text,
    fontSize: 10,
    fontWeight: "900",
  },
  profileSummaryCard: {
    backgroundColor: "#092117",
    borderRadius: 28,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    borderWidth: 2,
    borderColor: "#f1c75b",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 12,
  },
  profileAvatar: {
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: "#c9a45c",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#f5efe4",
  },
  profileAvatarText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
  },
  profileSummaryMain: {
    flex: 1,
  },
  profileWelcome: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  profileName: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 20,
    marginTop: 1,
  },
  profileSettingsButton: {
    backgroundColor: "rgba(245,239,228,0.18)",
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: "rgba(241,199,91,0.55)",
  },
  profileSettingsText: {
    color: "#f5efe4",
    fontWeight: "900",
    fontSize: 11,
  },
  profileStatsPanel: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  profileStatItem: {
    flex: 1,
    minHeight: 58,
    backgroundColor: "rgba(245,239,228,0.1)",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.16)",
    justifyContent: "center",
  },
  profileStatValue: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  profileStatLabel: {
    color: "#d8c5a7",
    fontSize: 9,
    fontWeight: "900",
    marginTop: 2,
    textTransform: "uppercase",
  },
  profileCardBackPreview: {
    width: 82,
    minHeight: 58,
    backgroundColor: "rgba(245,239,228,0.1)",
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileCardBackImage: {
    width: 24,
    height: 34,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.4)",
  },
  profileCardBackText: {
    color: "#f5efe4",
    fontSize: 8,
    fontWeight: "900",
    marginTop: 3,
    textAlign: "center",
  },
  profileTablePreview: {
    width: 82,
    minHeight: 58,
    backgroundColor: "rgba(245,239,228,0.1)",
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileTableRail: {
    position: "absolute",
    top: 7,
    width: 52,
    height: 30,
    borderRadius: 11,
    borderWidth: 2,
    opacity: 0.7,
  },
  profileTableFelt: {
    width: 42,
    height: 24,
    borderRadius: 9,
    borderWidth: 1,
  },
  profileSetupCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 22,
    padding: 13,
    gap: 9,
    borderWidth: 2,
    borderColor: "#c9a45c",
  },
  profileSetupEyebrow: {
    color: "#8c6b33",
    fontWeight: "900",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  profileSetupTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 20,
    marginTop: -4,
  },
  profileSetupText: {
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 17,
  },
  saveProfileButton: {
    backgroundColor: "#17352a",
    borderRadius: 16,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  saveProfileButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 15,
  },
  logoRow: {
    alignItems: "center",
    justifyContent: "center",
  },
  cardLogoSmall: {
    width: 68,
    height: 88,
    borderRadius: 14,
    backgroundColor: "#fbf8f1",
    borderWidth: 3,
    borderColor: "#17352a",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 5,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    elevation: 10,
    transform: [{ rotate: "-5deg" }],
  },
  cardLogoText: {
    alignSelf: "flex-start",
    marginLeft: 7,
    color: "#17352a",
    fontWeight: "900",
    fontSize: 14,
  },
  cardLogoIcon: {
    fontSize: 25,
    marginBottom: 3,
    color: "#17352a",
  },
  brandBadge: {
    marginTop: 10,
    alignSelf: "center",
    backgroundColor: "#092117",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderWidth: 2,
    borderColor: "#f1c75b",
  },
  brandBadgeText: {
    color: "#f5efe4",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.8,
  },
  homeTitle: {
    fontSize: 46,
    fontWeight: "900",
    color: "#10251d",
    textAlign: "center",
    letterSpacing: 0,
    marginTop: -2,
    textShadowColor: "rgba(201,164,92,0.45)",
    textShadowOffset: {
      width: 0,
      height: 3,
    },
    textShadowRadius: 0,
  },
  homeSubtitle: {
    fontSize: 15,
    color: "#5f5242",
    textAlign: "center",
    lineHeight: 21,
    fontWeight: "700",
    marginHorizontal: 6,
  },
  homeStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  walletMiniPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#092117",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 13,
    borderWidth: 2,
    borderColor: "#f1c75b",
  },
  walletMiniIcon: {
    width: 18,
    height: 18,
  },
  walletMiniText: {
    color: "#f5efe4",
    fontWeight: "900",
    fontSize: 12,
  },
  walletMiniDivider: {
    color: "#c9a45c",
    fontWeight: "900",
    fontSize: 12,
  },
  economyNotice: {
    backgroundColor: "#201427",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#f4b739",
    paddingVertical: 7,
    paddingHorizontal: 13,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 8,
  },
  economyNoticeText: {
    color: "#fff7e7",
    fontWeight: "900",
    fontSize: 12,
    textAlign: "center",
  },
  connectionHelpCard: {
    minHeight: 66,
    backgroundColor: "#fff7ed",
    borderRadius: 20,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#fdba74",
  },
  connectionHelpCopy: {
    flex: 1,
  },
  connectionHelpTitle: {
    color: "#9a3412",
    fontSize: 15,
    fontWeight: "900",
  },
  connectionHelpText: {
    color: "#7c2d12",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  connectionRetryButton: {
    minHeight: 38,
    borderRadius: 999,
    backgroundColor: "#17352a",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  connectionRetryText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  homeRewardCard: {
    minHeight: 66,
    backgroundColor: "#0b3a27",
    borderRadius: 24,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 2,
    borderColor: "#3ee58f",
    shadowColor: "#0f2f24",
    shadowOpacity: 0.34,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 7,
  },
  homeRewardIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: "rgba(245,239,228,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.18)",
  },
  homeRewardGemIcon: {
    width: 32,
    height: 32,
  },
  homeRewardCopy: {
    flex: 1,
  },
  homeRewardTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  homeRewardText: {
    color: "#d9e8df",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  homeRewardCta: {
    color: "#17352a",
    backgroundColor: "#f5efe4",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 13,
    paddingVertical: 8,
    fontSize: 12,
    fontWeight: "900",
  },
  economyPanel: {
    backgroundColor: "#10251d",
    borderRadius: 24,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  walletRow: {
    flexDirection: "row",
    gap: 8,
  },
  currencyPill: {
    flex: 1,
    backgroundColor: "#c9a45c",
    borderRadius: 17,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  currencyPillGem: {
    backgroundColor: "#2d6f92",
  },
  currencyPillEntry: {
    backgroundColor: "#1f7a54",
  },
  currencyPillTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  currencyIcon: {
    width: 22,
    height: 22,
  },
  currencyLabel: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  currencyValue: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    marginTop: 1,
  },
  seasonCard: {
    backgroundColor: "#f5efe4",
    borderRadius: 20,
    padding: 12,
    gap: 9,
  },
  seasonHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  seasonEyebrow: {
    color: "#8c6b33",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  seasonTitle: {
    color: "#10251d",
    fontSize: 18,
    fontWeight: "900",
  },
  seasonLevelBadge: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  seasonLevelText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  seasonProgressTrack: {
    height: 10,
    backgroundColor: "#d8c5a7",
    borderRadius: 999,
    overflow: "hidden",
  },
  seasonProgressFill: {
    height: "100%",
    backgroundColor: "#1f7a54",
    borderRadius: 999,
  },
  seasonProgressText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "800",
  },
  shopActionsRow: {
    flexDirection: "row",
    gap: 8,
  },
  shopButton: {
    flex: 1,
    backgroundColor: "#c9a45c",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "#8c6b33",
  },
  shopButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  shopButtonSub: {
    color: "#3b2417",
    fontWeight: "900",
    fontSize: 11,
    marginTop: 2,
  },
  premiumButton: {
    flex: 1,
    backgroundColor: "#17352a",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  premiumButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  premiumButtonSub: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 11,
    marginTop: 2,
  },
  rewardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  rewardCard: {
    width: "48%",
    minHeight: 78,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: "#8fc9a6",
    justifyContent: "space-between",
  },
  rewardCardLocked: {
    opacity: 0.62,
    borderColor: "#ded1bb",
  },
  rewardCardClaimed: {
    backgroundColor: "#edf8ef",
  },
  rewardLevel: {
    color: "#8c6b33",
    fontWeight: "900",
    fontSize: 10,
    textTransform: "uppercase",
  },
  rewardTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 12,
  },
  rewardMeta: {
    color: "#1f7a54",
    fontWeight: "900",
    fontSize: 10,
    marginTop: 4,
  },
  gameMenuPanel: {
    backgroundColor: "#ebe2d4",
    borderRadius: 22,
    padding: 15,
    gap: 12,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  gameMenuHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  gameMenuTitle: {
    color: "#10251d",
    fontSize: 19,
    fontWeight: "900",
  },
  gameMenuSubtitle: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  compactWalletPill: {
    backgroundColor: "#fbf8f1",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
    alignItems: "flex-end",
  },
  compactWalletText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 11,
  },
  playPanel: {
    backgroundColor: "#eadcc5",
    borderRadius: 28,
    padding: 14,
    gap: 12,
    borderWidth: 2,
    borderColor: "#d0ae68",
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 8,
  },
  playHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  playTitle: {
    color: "#10251d",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 0,
  },
  playSubtitle: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 1,
  },
  entryChip: {
    backgroundColor: "#fffaf0",
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: "#c9a45c",
    alignItems: "center",
  },
  entryChipLabel: {
    color: "#8c6b33",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  entryChipValue: {
    color: "#10251d",
    fontSize: 13,
    fontWeight: "900",
    marginTop: 1,
  },
  primaryPlayButton: {
    minHeight: 68,
    borderRadius: 25,
    backgroundColor: "#0f7a4d",
    borderWidth: 3,
    borderColor: "#073f2b",
    paddingVertical: 15,
    paddingHorizontal: 16,
    justifyContent: "center",
    shadowColor: "#052e1f",
    shadowOpacity: 0.46,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 14,
  },
  primaryPlayButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 22,
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.35)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  primaryPlayButtonSub: {
    color: "#d9e8df",
    fontWeight: "800",
    fontSize: 12,
    marginTop: 3,
  },
  joinCompactCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 24,
    padding: 12,
    gap: 8,
    borderWidth: 2,
    borderColor: "#d0ae68",
    overflow: "hidden",
  },
  joinCodeRow: {
    flexDirection: "column",
    gap: 8,
    alignItems: "stretch",
    width: "100%",
  },
  codeInputCompact: {
    width: "100%",
    minWidth: 0,
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#c9a45c",
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 23,
    color: "#111827",
    fontWeight: "900",
    letterSpacing: 2,
    textAlign: "center",
  },
  joinCompactButton: {
    minHeight: 52,
    width: "100%",
    borderRadius: 18,
    backgroundColor: "#d39b32",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#7a531c",
  },
  joinCompactButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 15,
  },
  rulesPreviewCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 20,
    padding: 13,
    borderWidth: 1,
    borderColor: "#ded1bb",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  rulesPreviewTitle: {
    color: "#10251d",
    fontSize: 16,
    fontWeight: "900",
  },
  rulesPreviewText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
    lineHeight: 17,
  },
  rulesPreviewCta: {
    color: "#ffffff",
    backgroundColor: "#17352a",
    borderRadius: 999,
    overflow: "hidden",
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 11,
    fontWeight: "900",
  },
  bigGameButton: {
    minHeight: 78,
    borderRadius: 22,
    backgroundColor: "#164636",
    borderWidth: 1,
    borderColor: "#0b2b21",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 12,
    shadowColor: "#0f2f24",
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 8,
  },
  bigGameButtonIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "rgba(245,239,228,0.16)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.35)",
  },
  bigGameButtonIconText: {
    color: "#ffffff",
    fontSize: 27,
    fontWeight: "900",
  },
  bigGameButtonTextBox: {
    flex: 1,
  },
  bigGameButtonTitle: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 17,
  },
  bigGameButtonSub: {
    color: "#d9e8df",
    fontWeight: "700",
    fontSize: 12,
    marginTop: 2,
  },
  joinCard: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  joinHeader: {
    gap: 1,
  },
  joinTitle: {
    color: "#10251d",
    fontSize: 17,
    fontWeight: "900",
  },
  joinSub: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
  },
  joinButton: {
    minHeight: 52,
    borderRadius: 17,
    backgroundColor: "#c08a2c",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#7a531c",
  },
  joinButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 16,
  },
  homeSecondaryActions: {
    flexDirection: "row",
    gap: 10,
  },
  homeSecondaryButton: {
    flex: 1,
    minHeight: 74,
    backgroundColor: "#10251d",
    borderRadius: 20,
    padding: 12,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  homeSecondaryButtonAlt: {
    flex: 1,
    minHeight: 74,
    backgroundColor: "#fbf8f1",
    borderRadius: 20,
    padding: 12,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  homeSecondaryTitle: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 14,
  },
  homeSecondaryText: {
    color: "#d8c5a7",
    fontWeight: "800",
    fontSize: 11,
    marginTop: 4,
  },
  homeSecondaryTitleAlt: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 14,
  },
  homeSecondaryTextAlt: {
    color: "#6d614f",
    fontWeight: "800",
    fontSize: 11,
    marginTop: 4,
  },
  gemChestButton: {
    flex: 1,
    backgroundColor: "#2d6f92",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "#7dd3fc",
  },
  gemChestButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  gemChestButtonSub: {
    color: "#dff7ff",
    fontWeight: "900",
    fontSize: 11,
    marginTop: 2,
  },
  shopModalCard: {
    maxHeight: "88%",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    backgroundColor: calmTheme.colors.surface,
  },
  shopModalScroll: {
    width: "100%",
  },
  shopNotice: {
    backgroundColor: "#fff7ed",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fdba74",
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  shopNoticeText: {
    color: "#9a3412",
    fontWeight: "900",
    fontSize: 12,
    textAlign: "center",
  },
  modalHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  modalTitleLeft: {
    color: "#10251d",
    fontSize: 31,
    fontWeight: "900",
    letterSpacing: 0,
  },
  modalTextLeft: {
    color: "#5f5242",
    fontWeight: "700",
    marginTop: 3,
  },
  modalCloseButton: {
    backgroundColor: "#e7ded0",
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  modalCloseText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 12,
  },
  settingsGroup: {
    width: "100%",
    gap: 10,
    marginTop: 2,
  },
  settingRow: {
    minHeight: 52,
    backgroundColor: "rgba(16,32,29,0.04)",
    borderRadius: 14,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  settingBlock: {
    backgroundColor: "rgba(16,32,29,0.04)",
    borderRadius: 14,
    padding: 11,
    gap: 8,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  settingLabel: {
    color: "#10251d",
    fontSize: 13,
    fontWeight: "900",
  },
  settingToggle: {
    width: 54,
    height: 30,
    borderRadius: 999,
    backgroundColor: calmTheme.colors.surfaceMuted,
    padding: 3,
    justifyContent: "center",
  },
  settingToggleOn: {
    backgroundColor: calmTheme.colors.secondary,
  },
  settingToggleKnob: {
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  settingToggleKnobOn: {
    alignSelf: "flex-end",
  },
  settingSegment: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  settingSegmentButton: {
    flexGrow: 1,
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  settingSegmentButtonOn: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderColor: calmTheme.colors.surfaceDark,
  },
  settingSegmentButtonDisabled: {
    opacity: 0.52,
    backgroundColor: "rgba(16,32,29,0.03)",
  },
  settingSegmentText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  settingSegmentTextOn: {
    color: "#f5efe4",
  },
  settingSegmentTextDisabled: {
    color: "#9a8f80",
  },
  settingSegmentSubText: {
    color: "#8d8274",
    fontSize: 8,
    fontWeight: "800",
    marginTop: 1,
  },
  settingHelperText: {
    color: calmTheme.colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 16,
  },
  rulesModalCard: {
    maxHeight: "86%",
  },
  rulesScroll: {
    width: "100%",
  },
  rulesList: {
    width: "100%",
    gap: 12,
    marginVertical: 4,
    paddingBottom: 2,
  },
  ruleSectionCard: {
    backgroundColor: calmTheme.colors.surface,
    borderRadius: calmTheme.radius.lg,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  ruleSectionTitle: {
    color: calmTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  ruleSectionIntro: {
    color: calmTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  ruleSectionList: {
    gap: 8,
  },
  ruleHelpItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 12,
    padding: 10,
  },
  ruleHelpCopy: {
    flex: 1,
    gap: 2,
  },
  ruleHelpBadge: {
    minWidth: 40,
    minHeight: 34,
    borderRadius: 12,
    backgroundColor: calmTheme.colors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  ruleHelpBadgeText: {
    color: calmTheme.colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  ruleHelpTitle: {
    color: "#10251d",
    fontSize: 13,
    fontWeight: "900",
  },
  ruleHelpText: {
    color: calmTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  shopSheet: {
    gap: 12,
  },
  shopHeaderCard: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: calmTheme.radius.xl,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  shopHeaderCopy: {
    gap: 4,
  },
  shopHeaderTitle: {
    color: calmTheme.colors.textOnDark,
    fontSize: 24,
    fontWeight: "900",
  },
  shopHeaderText: {
    color: calmTheme.colors.textOnDarkMuted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  shopBalanceRow: {
    flexDirection: "row",
    gap: 8,
  },
  shopTabBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 16,
    padding: 4,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  shopTabButton: {
    flex: 1,
    minWidth: 82,
    minHeight: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  shopTabButtonActive: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderWidth: 1,
    borderColor: calmTheme.colors.surfaceDark,
  },
  shopTabText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "900",
  },
  shopTabTextActive: {
    color: "#f5efe4",
  },
  shopSection: {
    backgroundColor: calmTheme.colors.surface,
    borderRadius: calmTheme.radius.xl,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 1,
  },
  shopSectionTitle: {
    color: calmTheme.colors.text,
    fontWeight: "900",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  shopSectionSubtitle: {
    color: calmTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    marginTop: 4,
  },
  dailyRewardCard: {
    backgroundColor: calmTheme.colors.surface,
    borderRadius: calmTheme.radius.xl,
    padding: 14,
    minHeight: 90,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  dailyRewardCardClaimed: {
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderColor: calmTheme.colors.border,
  },
  dailyRewardCopy: {
    flex: 1,
    minWidth: 0,
  },
  dailyRewardTitle: {
    color: calmTheme.colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  dailyRewardText: {
    color: calmTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
    lineHeight: 17,
  },
  dailyRewardAction: {
    minWidth: 88,
    minHeight: 38,
    borderRadius: 999,
    backgroundColor: calmTheme.colors.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  dailyRewardActionClaimed: {
    backgroundColor: calmTheme.colors.surfaceDark,
  },
  dailyRewardValue: {
    color: calmTheme.colors.textOnDark,
    fontSize: 12,
    fontWeight: "900",
  },
  shopProductList: {
    gap: 10,
  },
  shopProductCard: {
    minHeight: 76,
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 16,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  shopProductPlaceholder: {
    opacity: 0.9,
  },
  shopProductPreview: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: calmTheme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  shopProductImage: {
    width: 34,
    height: 34,
  },
  shopProductIcon: {
    color: calmTheme.colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  shopProductCopy: {
    flex: 1,
    minWidth: 0,
  },
  shopProductTitle: {
    color: calmTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  shopProductText: {
    color: calmTheme.colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
    marginTop: 2,
  },
  shopProductAction: {
    minWidth: 82,
    minHeight: 36,
    borderRadius: 999,
    backgroundColor: calmTheme.colors.surfaceDark,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  shopProductActionPlaceholder: {
    backgroundColor: "#e7ded0",
  },
  shopProductActionText: {
    color: calmTheme.colors.textOnDark,
    fontSize: 11,
    fontWeight: "900",
  },
  shopProductActionTextPlaceholder: {
    color: calmTheme.colors.textMuted,
  },
  gemPurchaseCard: {
    minHeight: 86,
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 15,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  shopActionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 17,
    backgroundColor: "rgba(245,239,228,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.2)",
  },
  shopActionIcon: {
    width: 36,
    height: 36,
  },
  shopActionTextBox: {
    flex: 1,
  },
  gemPurchaseTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  gemPurchaseText: {
    color: "#d9e8df",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
    lineHeight: 17,
  },
  exchangeCard: {
    backgroundColor: calmTheme.colors.accentSoft,
    borderRadius: 15,
    padding: 14,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  exchangeIconRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  exchangeIcon: {
    width: 42,
    height: 42,
  },
  exchangeTitle: {
    color: calmTheme.colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  exchangeText: {
    color: "#3b2417",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 3,
  },
  premiumPassCard: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 15,
    padding: 14,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  premiumPassTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  premiumPassText: {
    color: "#d8c5a7",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  cardBackCollectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  cardBackCollectionSubtitle: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  collectionPercentPill: {
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  collectionPercentText: {
    color: calmTheme.colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  cardBackShowcase: {
    minHeight: 162,
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 20,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    overflow: "hidden",
  },
  cardBackShowcaseStack: {
    width: 118,
    height: 138,
    alignItems: "center",
    justifyContent: "center",
  },
  cardBackShowcaseImage: {
    position: "absolute",
    width: 84,
    height: 122,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(247,243,236,0.42)",
    backgroundColor: "#10251d",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 4,
    transform: [{ rotate: "0deg" }],
  },
  cardBackShowcaseGhost: {
    opacity: 0.52,
    transform: [{ translateX: -22 }, { rotate: "-10deg" }],
  },
  cardBackShowcaseGhostTwo: {
    opacity: 0.7,
    transform: [{ translateX: 22 }, { rotate: "10deg" }],
  },
  cardBackShowcaseCopy: {
    flex: 1,
    gap: 5,
  },
  cardBackShowcaseEyebrow: {
    color: "#d8c5a7",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  cardBackShowcaseTitle: {
    color: "#ffffff",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 0,
  },
  cardBackShowcaseText: {
    color: "#d9e8df",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  cardBackShowcaseBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(201,164,92,0.18)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.65)",
    marginTop: 3,
  },
  cardBackShowcaseBadgeText: {
    color: "#f5efe4",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  shopFeatureCard: {
    minHeight: 86,
    backgroundColor: "#fffaf0",
    borderRadius: 15,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  shopFeatureCardBuyable: {
    borderColor: calmTheme.colors.border,
    backgroundColor: calmTheme.colors.surface,
  },
  shopFeatureCardDisabled: {
    opacity: 0.72,
  },
  shopFeatureImage: {
    width: 46,
    height: 66,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d8c5a7",
    backgroundColor: "#10251d",
  },
  shopFeatureCopy: {
    flex: 1,
  },
  shopFeatureEyebrow: {
    color: "#8c6b33",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  shopFeatureTitle: {
    color: "#10251d",
    fontSize: 17,
    fontWeight: "900",
    marginTop: 2,
  },
  shopFeatureMeta: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
    marginTop: 3,
  },
  shopFeatureCta: {
    minWidth: 82,
    minHeight: 38,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  shopFeatureCtaStrong: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderColor: calmTheme.colors.surfaceDark,
  },
  shopFeatureCtaText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  shopFeatureCtaTextStrong: {
    color: "#ffffff",
  },
  cardBackFilterBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  cardBackFilterChip: {
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    paddingHorizontal: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  cardBackFilterChipOn: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderColor: calmTheme.colors.surfaceDark,
  },
  cardBackFilterText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  cardBackFilterTextOn: {
    color: "#f5efe4",
  },
  cardBackShopGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
  },
  cardBackShopItem: {
    width: "48%",
    minWidth: 146,
    backgroundColor: calmTheme.colors.surface,
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 1,
  },
  cardBackShopItemSelected: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.42)",
  },
  cardBackShopItemLocked: {
    opacity: 0.84,
  },
  cardBackShopItemBuyable: {
    borderColor: calmTheme.colors.border,
    backgroundColor: calmTheme.colors.surface,
  },
  cardBackShopItemDisabled: {
    opacity: 0.68,
  },
  cardBackImageStage: {
    width: "100%",
    minHeight: 164,
    borderRadius: 21,
    backgroundColor: calmTheme.colors.surfaceDark,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  cardBackShopImage: {
    width: 104,
    height: 148,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#f5efe4",
    backgroundColor: "#10251d",
  },
  cardBackRarityBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "rgba(245,239,228,0.92)",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  cardBackRarityText: {
    color: "#17352a",
    fontSize: 8,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  cardBackShopTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
  },
  cardBackShopDescription: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 14,
    textAlign: "center",
    minHeight: 28,
  },
  cardBackPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#efe1c4",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  cardBackPriceIcon: {
    width: 16,
    height: 16,
  },
  cardBackPriceText: {
    color: "#6b512b",
    fontSize: 11,
    fontWeight: "900",
  },
  cardBackCta: {
    width: "100%",
    minHeight: 38,
    borderRadius: 16,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  cardBackCtaSelected: {
    backgroundColor: calmTheme.colors.secondary,
    borderColor: calmTheme.colors.secondary,
  },
  cardBackCtaOwned: {
    backgroundColor: calmTheme.colors.surfaceDark,
    borderColor: calmTheme.colors.surfaceDark,
  },
  cardBackCtaBuyable: {
    backgroundColor: calmTheme.colors.accent,
    borderColor: calmTheme.colors.accent,
  },
  cardBackCtaText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "900",
  },
  cardBackCtaTextStrong: {
    color: "#ffffff",
  },
  cardBackShopMeta: {
    color: "#6d614f",
    fontSize: 9,
    fontWeight: "900",
    textAlign: "center",
  },
  shopEmptyState: {
    minHeight: 86,
    borderRadius: 18,
    backgroundColor: "#efe7da",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cdbd9f",
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
  },
  shopEmptyTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  shopEmptyText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 3,
  },
  tableSkinGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
  },
  tableSkinCard: {
    width: "48%",
    minWidth: 146,
    backgroundColor: "#fffdf7",
    borderRadius: 24,
    padding: 10,
    gap: 8,
    borderWidth: 2,
    borderColor: "#ded1bb",
  },
  tableSkinCardSelected: {
    backgroundColor: "#e9fbea",
    borderColor: "#18a85e",
  },
  tableSkinCardBuyable: {
    backgroundColor: "#fffaf0",
    borderColor: "#c9a45c",
  },
  tableSkinCardDisabled: {
    opacity: 0.68,
  },
  tableSkinPreview: {
    height: 98,
    borderRadius: 22,
    backgroundColor: "#092117",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "rgba(241,199,91,0.65)",
  },
  tableSkinFelt: {
    width: 104,
    height: 64,
    borderRadius: 22,
    borderWidth: 3,
  },
  tableSkinRail: {
    position: "absolute",
    width: 132,
    height: 88,
    borderRadius: 30,
    borderWidth: 5,
    opacity: 0.42,
  },
  tableSkinTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  tableSkinMeta: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  tableSkinCta: {
    minHeight: 36,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  tableSkinCtaStrong: {
    backgroundColor: "#17352a",
    borderColor: "#c9a45c",
  },
  tableSkinCtaText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  tableSkinCtaTextStrong: {
    color: "#ffffff",
  },
  cosmeticGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
  },
  cosmeticCard: {
    width: "48%",
    minWidth: 146,
    backgroundColor: "#fffdf7",
    borderRadius: 24,
    padding: 11,
    gap: 7,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ded1bb",
  },
  cosmeticCardSelected: {
    backgroundColor: "#edf8ef",
    borderColor: "#1f7a54",
  },
  cosmeticCardBuyable: {
    backgroundColor: "#fffaf0",
    borderColor: "#f1c75b",
  },
  cosmeticCardDisabled: {
    opacity: 0.68,
  },
  cosmeticAvatarPreview: {
    width: 70,
    height: 70,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#f5efe4",
  },
  cosmeticAvatarText: {
    fontSize: 31,
    fontWeight: "900",
  },
  cosmeticFramePreview: {
    width: 72,
    height: 72,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 4,
    shadowOpacity: 0.5,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 8,
  },
  cosmeticFrameText: {
    color: "#f5efe4",
    fontSize: 30,
    fontWeight: "900",
  },
  cosmeticTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
  },
  cosmeticMeta: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "900",
  },
  cosmeticCta: {
    width: "100%",
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "#17352a",
    color: "#ffffff",
    textAlign: "center",
    paddingVertical: 8,
    paddingHorizontal: 8,
    fontSize: 11,
    fontWeight: "900",
  },
  dailyMissionItem: {
    borderColor: "#c9a45c",
    backgroundColor: "#fff7df",
  },
  previewModalCard: {
    maxWidth: 430,
  },
  previewStage: {
    minHeight: 210,
    borderRadius: 28,
    backgroundColor: "#092117",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 3,
    borderColor: "#f1c75b",
  },
  previewCardBackImage: {
    width: 128,
    height: 184,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#f5efe4",
  },
  previewTable: {
    width: 240,
    height: 150,
    alignItems: "center",
    justifyContent: "center",
  },
  previewTableRail: {
    position: "absolute",
    width: 230,
    height: 140,
    borderRadius: 42,
    borderWidth: 6,
    opacity: 0.9,
  },
  previewTableFelt: {
    width: 184,
    height: 104,
    borderRadius: 34,
    borderWidth: 3,
  },
  previewAvatar: {
    width: 128,
    height: 128,
    borderRadius: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderColor: "#f5efe4",
  },
  previewAvatarText: {
    color: "#f5efe4",
    fontSize: 58,
    fontWeight: "900",
  },
  previewEyebrow: {
    color: "#8c6b33",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  previewTitle: {
    color: "#10251d",
    fontSize: 27,
    fontWeight: "900",
    textAlign: "center",
  },
  previewText: {
    color: "#6d614f",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 18,
  },
  comingSoonCard: {
    minHeight: 170,
    backgroundColor: "#10251d",
    borderRadius: 24,
    padding: 18,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  comingSoonEyebrow: {
    color: "#d8c5a7",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  comingSoonTitle: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "900",
    marginTop: 4,
  },
  comingSoonText: {
    color: "#d9e8df",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
    marginTop: 6,
  },
  milestoneCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 18,
    padding: 12,
    gap: 9,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  milestoneCardReady: {
    borderColor: "#1f7a54",
    backgroundColor: "#edf8ef",
  },
  milestoneCardClaimed: {
    opacity: 0.66,
  },
  milestoneTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  milestoneCopy: {
    flex: 1,
  },
  milestoneTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  milestoneText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  milestoneRewardPill: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  milestoneRewardText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  milestoneProgressTrack: {
    height: 9,
    backgroundColor: "#d8c5a7",
    borderRadius: 999,
    overflow: "hidden",
  },
  milestoneProgressFill: {
    height: "100%",
    backgroundColor: "#1f7a54",
    borderRadius: 999,
  },
  milestoneBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  milestoneProgressText: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "900",
  },
  milestoneActionText: {
    color: "#1f7a54",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  quickRulesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
  },
  rulePill: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.45)",
  },
  rulePillText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  homeFooterText: {
    textAlign: "center",
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
  },
  lobbyScroll: {
    flexGrow: 1,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 22,
    justifyContent: "flex-start",
  },
  lobbyPanel: {
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
    backgroundColor: calmTheme.colors.surfaceDark,
    borderRadius: 22,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 6,
    overflow: "hidden",
  },
  lobbyGlowGold: {
    position: "absolute",
    top: -68,
    right: -58,
    width: 170,
    height: 170,
    borderRadius: 999,
    backgroundColor: "rgba(255,205,88,0.20)",
  },
  lobbyGlowGreen: {
    position: "absolute",
    bottom: 90,
    left: -82,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: "rgba(48,219,125,0.12)",
  },
  lobbyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  lobbyHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  lobbyEyebrow: {
    color: calmTheme.colors.accentStrong,
    fontWeight: "900",
    fontSize: 12,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  lobbyTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 0,
  },
  lobbySubtitle: {
    color: "#d8c5a7",
    fontWeight: "800",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
    maxWidth: 285,
  },
  playerCountPill: {
    flexShrink: 0,
    backgroundColor: "rgba(247,243,236,0.10)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  playerCountText: {
    color: calmTheme.colors.textOnDark,
    fontWeight: "900",
    fontSize: 16,
  },
  codeHeroCard: {
    backgroundColor: "rgba(247,243,236,0.08)",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 2,
  },
  codeHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  codeLabel: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  codeValue: {
    color: "#fbf8f1",
    fontWeight: "900",
    fontSize: 34,
    letterSpacing: 2,
    marginTop: 3,
  },
  codeActionsVertical: {
    gap: 8,
    minWidth: 88,
  },
  codeActionButton: {
    backgroundColor: "rgba(247,243,236,0.08)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
  },
  codeActionText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  codeActionButtonGold: {
    backgroundColor: calmTheme.colors.accent,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  codeActionTextGold: {
    color: "#4a2f0d",
    fontWeight: "900",
    fontSize: 12,
  },
  lobbyArenaStrip: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(255,255,255,0.09)",
    borderRadius: 19,
    padding: 9,
    borderWidth: 1,
    borderColor: "rgba(255,208,87,0.35)",
  },
  lobbyArenaIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: "#7c3aed",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#d8b4fe",
  },
  lobbyArenaIconText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
  },
  lobbyArenaCopy: {
    flex: 1,
  },
  lobbyArenaTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
  },
  lobbyArenaText: {
    color: "#d8c5a7",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 2,
  },
  lobbyArenaBadge: {
    backgroundColor: "#f4b739",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  lobbyArenaBadgeText: {
    color: "#4a2f0d",
    fontSize: 10,
    fontWeight: "900",
  },
  roomStepCard: {
    minHeight: 66,
    backgroundColor: "#f6efe1",
    borderRadius: 21,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 2,
    borderColor: "#d6b35c",
  },
  roomStepBadge: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: "#17352a",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  roomStepBadgeText: {
    color: "#f5efe4",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  roomStepCopy: {
    flex: 1,
  },
  roomStepTitle: {
    color: "#10251d",
    fontSize: 18,
    fontWeight: "900",
  },
  roomStepText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  lobbyStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  hostPill: {
    backgroundColor: "#ebe2d4",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  hostPillText: {
    color: "#6b512b",
    fontWeight: "900",
    fontSize: 12,
  },
  readyCard: {
    backgroundColor: "rgba(247,243,236,0.07)",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  readyTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  readyCopy: {
    flex: 1,
    minWidth: 0,
  },
  readyTitle: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 15,
  },
  readyNumber: {
    color: "#50e78c",
    fontWeight: "900",
    fontSize: 15,
  },
  lobbyOnlinePill: {
    flexShrink: 0,
    backgroundColor: "rgba(247,243,236,0.10)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  lobbyOnlinePillText: {
    color: calmTheme.colors.textOnDark,
    fontSize: 11,
    fontWeight: "900",
  },
  progressTrack: {
    height: 11,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 10,
  },
  progressFill: {
    height: "100%",
    backgroundColor: calmTheme.colors.secondary,
    borderRadius: 999,
  },
  roomFactsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  roomFactChip: {
    backgroundColor: "rgba(255,255,255,0.09)",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.13)",
  },
  roomFactText: {
    color: "#d8c5a7",
    fontSize: 11,
    fontWeight: "900",
  },
  readyHelper: {
    marginTop: 2,
    color: "#d8c5a7",
    fontWeight: "800",
    fontSize: 12,
  },
  nameEditCard: {
    backgroundColor: "#fbf8f1",
    borderRadius: 20,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  nameEditHelper: {
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 11,
  },
  profileLockedName: {
    color: "#10251d",
    fontSize: 20,
    fontWeight: "900",
  },
  playersSection: {
    backgroundColor: "rgba(247,243,236,0.07)",
    borderRadius: 18,
    padding: 9,
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  playerListTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 4,
    paddingBottom: 2,
  },
  playerListTitle: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 16,
  },
  playerListMeta: {
    color: calmTheme.colors.textOnDarkMuted,
    fontWeight: "800",
    fontSize: 12,
  },
  playerSlotCard: {
    width: "48%",
    minHeight: 142,
    backgroundColor: "#fbf8f1",
    borderRadius: 22,
    padding: 12,
    borderWidth: 1,
    borderColor: "#ded1bb",
    justifyContent: "space-between",
  },
  playerSlotReady: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.44)",
  },
  playerSlotOffline: {
    opacity: 0.45,
  },
  emptySlotCard: {
    width: "48%",
    minHeight: 142,
    backgroundColor: "#efe7da",
    borderRadius: 22,
    padding: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cdbd9f",
    justifyContent: "center",
    alignItems: "center",
  },
  playerRowCard: {
    minHeight: 64,
    backgroundColor: calmTheme.colors.surface,
    borderRadius: 15,
    padding: 10,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  playerRowMain: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  playerRowRight: {
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "space-between",
    minHeight: 52,
  },
  emptySlotRow: {
    minHeight: 54,
    backgroundColor: "rgba(247,243,236,0.72)",
    borderRadius: 15,
    padding: 11,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cdbd9f",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  emptySlotCopy: {
    flex: 1,
  },
  slotTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  slotAvatar: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: calmTheme.colors.surfaceDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  slotAvatarText: {
    color: "#ffffff",
    fontSize: 21,
    fontWeight: "900",
  },
  slotStatusDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
  },
  slotStatusOnline: {
    backgroundColor: "#22c55e",
  },
  slotStatusOffline: {
    backgroundColor: "#ef4444",
  },
  slotName: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 16,
  },
  slotTags: {
    flexDirection: "row",
    gap: 5,
    flexWrap: "wrap",
    minHeight: 24,
  },
  hostTag: {
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  hostTagText: {
    color: "#6b512b",
    fontWeight: "900",
    fontSize: 10,
  },
  youTag: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  youTagText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 10,
  },
  readyMiniBadge: {
    alignSelf: "flex-start",
    backgroundColor: calmTheme.colors.surfaceMuted,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  readyMiniBadgeOn: {
    backgroundColor: "#dcefe2",
  },
  readyMiniBadgeText: {
    color: "#6b7280",
    fontWeight: "900",
    fontSize: 11,
  },
  readyMiniBadgeTextOn: {
    color: "#1f7a54",
  },
  emptyAvatar: {
    width: 44,
    height: 44,
    borderRadius: 18,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyAvatarText: {
    color: "#9ca3af",
    fontWeight: "900",
    fontSize: 24,
  },
  emptySlotTitle: {
    color: "#6b7280",
    fontWeight: "900",
  },
  emptySlotText: {
    color: "#9ca3af",
    fontWeight: "800",
    fontSize: 12,
  },
  lobbyBottomPanel: {
    backgroundColor: "rgba(247,243,236,0.07)",
    borderRadius: 18,
    padding: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  readyCtaButton: {
    backgroundColor: calmTheme.colors.surface,
    minHeight: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  readyCtaButtonOn: {
    backgroundColor: calmTheme.colors.secondarySoft,
    borderColor: "rgba(111,174,148,0.52)",
  },
  readyCtaText: {
    color: "#374151",
    fontWeight: "900",
    fontSize: 16,
  },
  readyCtaTextOn: {
    color: calmTheme.colors.text,
  },
  hostControlNotice: {
    minHeight: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e6eee9",
    borderWidth: 1,
    borderColor: "#8fc9a6",
    paddingHorizontal: 14,
  },
  hostControlNoticeText: {
    color: "#17352a",
    fontWeight: "800",
    textAlign: "center",
  },
  startButton: {
    backgroundColor: calmTheme.colors.accent,
    minHeight: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  startButtonText: {
    color: calmTheme.colors.text,
    fontWeight: "900",
    fontSize: 17,
    textShadowRadius: 0,
  },
  hostWaitingBox: {
    minHeight: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: calmTheme.colors.surfaceMuted,
  },
  hostWaitingText: {
    color: "#6b7280",
    fontWeight: "900",
  },
  leaveButtonWide: {
    minHeight: 44,
    backgroundColor: "rgba(216,93,93,0.08)",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(216,93,93,0.24)",
  },
  leaveButtonText: {
    color: calmTheme.colors.danger,
    fontWeight: "900",
    fontSize: 13,
  },
});
