import { StyleSheet } from "react-native";

export const lobbyStyles = StyleSheet.create({
  homeScroll: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 18,
    paddingBottom: 34,
  },
  homeCard: {
    width: "100%",
    maxWidth: 540,
    alignSelf: "center",
    backgroundColor: "#f5efe4",
    borderRadius: 28,
    padding: 24,
    gap: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.58)",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 28,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 16,
  },
  profileSummaryCard: {
    backgroundColor: "#10251d",
    borderRadius: 24,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  profileAvatar: {
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: "#c9a45c",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#f5efe4",
  },
  profileAvatarText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
  },
  profileSummaryMain: {
    flex: 1,
  },
  profileWelcome: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  profileName: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 20,
    marginTop: 1,
  },
  profileSettingsButton: {
    backgroundColor: "rgba(245,239,228,0.12)",
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.20)",
  },
  profileSettingsText: {
    color: "#f5efe4",
    fontWeight: "900",
    fontSize: 11,
  },
  profileStatsPanel: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
    marginTop: 2,
  },
  profileStatItem: {
    flex: 1,
    minHeight: 58,
    backgroundColor: "rgba(245,239,228,0.1)",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.16)",
    justifyContent: "center",
  },
  profileStatValue: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  profileStatLabel: {
    color: "#d8c5a7",
    fontSize: 9,
    fontWeight: "900",
    marginTop: 2,
    textTransform: "uppercase",
  },
  profileCardBackPreview: {
    width: 82,
    minHeight: 58,
    backgroundColor: "rgba(245,239,228,0.1)",
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileCardBackImage: {
    width: 24,
    height: 34,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.4)",
  },
  profileCardBackText: {
    color: "#f5efe4",
    fontSize: 8,
    fontWeight: "900",
    marginTop: 3,
    textAlign: "center",
  },
  profileSetupCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 24,
    padding: 15,
    gap: 10,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  profileSetupEyebrow: {
    color: "#8c6b33",
    fontWeight: "900",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  profileSetupTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 22,
    marginTop: -4,
  },
  profileSetupText: {
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 17,
  },
  saveProfileButton: {
    backgroundColor: "#17352a",
    borderRadius: 16,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  saveProfileButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 15,
  },
  logoRow: {
    alignItems: "center",
    justifyContent: "center",
  },
  cardLogoSmall: {
    width: 58,
    height: 76,
    borderRadius: 10,
    backgroundColor: "#fbf8f1",
    borderWidth: 1,
    borderColor: "#d7c6a8",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 5,
    transform: [{ rotate: "-4deg" }],
  },
  cardLogoText: {
    alignSelf: "flex-start",
    marginLeft: 7,
    color: "#17352a",
    fontWeight: "900",
    fontSize: 14,
  },
  cardLogoIcon: {
    fontSize: 25,
    marginBottom: 3,
    color: "#17352a",
  },
  brandBadge: {
    marginTop: 10,
    alignSelf: "center",
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  brandBadgeText: {
    color: "#f5efe4",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.8,
  },
  homeTitle: {
    fontSize: 44,
    fontWeight: "900",
    color: "#10251d",
    textAlign: "center",
    letterSpacing: -1.4,
    marginTop: -2,
  },
  homeSubtitle: {
    fontSize: 15,
    color: "#5f5242",
    textAlign: "center",
    lineHeight: 21,
    fontWeight: "700",
    marginHorizontal: 6,
  },
  homeStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  walletMiniPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  walletMiniIcon: {
    width: 18,
    height: 18,
  },
  walletMiniText: {
    color: "#f5efe4",
    fontWeight: "900",
    fontSize: 12,
  },
  walletMiniDivider: {
    color: "#c9a45c",
    fontWeight: "900",
    fontSize: 12,
  },
  economyNotice: {
    backgroundColor: "#fff7ed",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fdba74",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  economyNoticeText: {
    color: "#9a3412",
    fontWeight: "900",
    fontSize: 12,
    textAlign: "center",
  },
  connectionHelpCard: {
    minHeight: 66,
    backgroundColor: "#fff7ed",
    borderRadius: 20,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#fdba74",
  },
  connectionHelpCopy: {
    flex: 1,
  },
  connectionHelpTitle: {
    color: "#9a3412",
    fontSize: 15,
    fontWeight: "900",
  },
  connectionHelpText: {
    color: "#7c2d12",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  connectionRetryButton: {
    minHeight: 38,
    borderRadius: 999,
    backgroundColor: "#17352a",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  connectionRetryText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  homeRewardCard: {
    minHeight: 66,
    backgroundColor: "#17352a",
    borderRadius: 21,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#8fc9a6",
    shadowColor: "#0f2f24",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 7,
  },
  homeRewardIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: "rgba(245,239,228,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.18)",
  },
  homeRewardGemIcon: {
    width: 32,
    height: 32,
  },
  homeRewardCopy: {
    flex: 1,
  },
  homeRewardTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  homeRewardText: {
    color: "#d9e8df",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  homeRewardCta: {
    color: "#17352a",
    backgroundColor: "#f5efe4",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 13,
    paddingVertical: 8,
    fontSize: 12,
    fontWeight: "900",
  },
  economyPanel: {
    backgroundColor: "#10251d",
    borderRadius: 24,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  walletRow: {
    flexDirection: "row",
    gap: 8,
  },
  currencyPill: {
    flex: 1,
    backgroundColor: "#c9a45c",
    borderRadius: 17,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  currencyPillGem: {
    backgroundColor: "#2d6f92",
  },
  currencyPillEntry: {
    backgroundColor: "#1f7a54",
  },
  currencyPillTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  currencyIcon: {
    width: 22,
    height: 22,
  },
  currencyLabel: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  currencyValue: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    marginTop: 1,
  },
  seasonCard: {
    backgroundColor: "#f5efe4",
    borderRadius: 20,
    padding: 12,
    gap: 9,
  },
  seasonHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  seasonEyebrow: {
    color: "#8c6b33",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  seasonTitle: {
    color: "#10251d",
    fontSize: 18,
    fontWeight: "900",
  },
  seasonLevelBadge: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  seasonLevelText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  seasonProgressTrack: {
    height: 10,
    backgroundColor: "#d8c5a7",
    borderRadius: 999,
    overflow: "hidden",
  },
  seasonProgressFill: {
    height: "100%",
    backgroundColor: "#1f7a54",
    borderRadius: 999,
  },
  seasonProgressText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "800",
  },
  shopActionsRow: {
    flexDirection: "row",
    gap: 8,
  },
  shopButton: {
    flex: 1,
    backgroundColor: "#c9a45c",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "#8c6b33",
  },
  shopButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  shopButtonSub: {
    color: "#3b2417",
    fontWeight: "900",
    fontSize: 11,
    marginTop: 2,
  },
  premiumButton: {
    flex: 1,
    backgroundColor: "#17352a",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  premiumButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  premiumButtonSub: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 11,
    marginTop: 2,
  },
  rewardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  rewardCard: {
    width: "48%",
    minHeight: 78,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: "#8fc9a6",
    justifyContent: "space-between",
  },
  rewardCardLocked: {
    opacity: 0.62,
    borderColor: "#ded1bb",
  },
  rewardCardClaimed: {
    backgroundColor: "#edf8ef",
  },
  rewardLevel: {
    color: "#8c6b33",
    fontWeight: "900",
    fontSize: 10,
    textTransform: "uppercase",
  },
  rewardTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 12,
  },
  rewardMeta: {
    color: "#1f7a54",
    fontWeight: "900",
    fontSize: 10,
    marginTop: 4,
  },
  gameMenuPanel: {
    backgroundColor: "#ebe2d4",
    borderRadius: 22,
    padding: 15,
    gap: 12,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  gameMenuHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  gameMenuTitle: {
    color: "#10251d",
    fontSize: 19,
    fontWeight: "900",
  },
  gameMenuSubtitle: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  compactWalletPill: {
    backgroundColor: "#fbf8f1",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
    alignItems: "flex-end",
  },
  compactWalletText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 11,
  },
  playPanel: {
    backgroundColor: "#ebe2d4",
    borderRadius: 24,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  playHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  playTitle: {
    color: "#10251d",
    fontSize: 22,
    fontWeight: "900",
  },
  playSubtitle: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 1,
  },
  entryChip: {
    backgroundColor: "#fbf8f1",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#ded1bb",
    alignItems: "center",
  },
  entryChipLabel: {
    color: "#8c6b33",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  entryChipValue: {
    color: "#10251d",
    fontSize: 13,
    fontWeight: "900",
    marginTop: 1,
  },
  primaryPlayButton: {
    minHeight: 62,
    borderRadius: 22,
    backgroundColor: "#164636",
    borderWidth: 1,
    borderColor: "#0b2b21",
    paddingVertical: 15,
    paddingHorizontal: 16,
    justifyContent: "center",
    shadowColor: "#0f2f24",
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 8,
  },
  primaryPlayButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 18,
  },
  primaryPlayButtonSub: {
    color: "#d9e8df",
    fontWeight: "800",
    fontSize: 12,
    marginTop: 3,
  },
  joinCompactCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  joinCodeRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  codeInputCompact: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#bfa77f",
    borderRadius: 15,
    paddingVertical: 13,
    paddingHorizontal: 14,
    fontSize: 21,
    color: "#111827",
    fontWeight: "900",
    letterSpacing: 2,
    textAlign: "center",
  },
  joinCompactButton: {
    minHeight: 52,
    minWidth: 82,
    borderRadius: 16,
    backgroundColor: "#c08a2c",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#7a531c",
  },
  joinCompactButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 15,
  },
  rulesPreviewCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 20,
    padding: 13,
    borderWidth: 1,
    borderColor: "#ded1bb",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  rulesPreviewTitle: {
    color: "#10251d",
    fontSize: 16,
    fontWeight: "900",
  },
  rulesPreviewText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
    lineHeight: 17,
  },
  rulesPreviewCta: {
    color: "#ffffff",
    backgroundColor: "#17352a",
    borderRadius: 999,
    overflow: "hidden",
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 11,
    fontWeight: "900",
  },
  bigGameButton: {
    minHeight: 78,
    borderRadius: 22,
    backgroundColor: "#164636",
    borderWidth: 1,
    borderColor: "#0b2b21",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 12,
    shadowColor: "#0f2f24",
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 8,
  },
  bigGameButtonIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "rgba(245,239,228,0.16)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.35)",
  },
  bigGameButtonIconText: {
    color: "#ffffff",
    fontSize: 27,
    fontWeight: "900",
  },
  bigGameButtonTextBox: {
    flex: 1,
  },
  bigGameButtonTitle: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 17,
  },
  bigGameButtonSub: {
    color: "#d9e8df",
    fontWeight: "700",
    fontSize: 12,
    marginTop: 2,
  },
  joinCard: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  joinHeader: {
    gap: 1,
  },
  joinTitle: {
    color: "#10251d",
    fontSize: 17,
    fontWeight: "900",
  },
  joinSub: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
  },
  joinButton: {
    minHeight: 52,
    borderRadius: 17,
    backgroundColor: "#c08a2c",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#7a531c",
  },
  joinButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 16,
  },
  homeSecondaryActions: {
    flexDirection: "row",
    gap: 10,
  },
  homeSecondaryButton: {
    flex: 1,
    minHeight: 74,
    backgroundColor: "#10251d",
    borderRadius: 20,
    padding: 12,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  homeSecondaryButtonAlt: {
    flex: 1,
    minHeight: 74,
    backgroundColor: "#fbf8f1",
    borderRadius: 20,
    padding: 12,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  homeSecondaryTitle: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 14,
  },
  homeSecondaryText: {
    color: "#d8c5a7",
    fontWeight: "800",
    fontSize: 11,
    marginTop: 4,
  },
  homeSecondaryTitleAlt: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 14,
  },
  homeSecondaryTextAlt: {
    color: "#6d614f",
    fontWeight: "800",
    fontSize: 11,
    marginTop: 4,
  },
  gemChestButton: {
    flex: 1,
    backgroundColor: "#2d6f92",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "#7dd3fc",
  },
  gemChestButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  gemChestButtonSub: {
    color: "#dff7ff",
    fontWeight: "900",
    fontSize: 11,
    marginTop: 2,
  },
  shopModalCard: {
    maxHeight: "88%",
  },
  shopModalScroll: {
    width: "100%",
  },
  shopNotice: {
    backgroundColor: "#fff7ed",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fdba74",
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  shopNoticeText: {
    color: "#9a3412",
    fontWeight: "900",
    fontSize: 12,
    textAlign: "center",
  },
  modalHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  modalTitleLeft: {
    color: "#10251d",
    fontSize: 28,
    fontWeight: "900",
  },
  modalTextLeft: {
    color: "#5f5242",
    fontWeight: "700",
    marginTop: 3,
  },
  modalCloseButton: {
    backgroundColor: "#e7ded0",
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  modalCloseText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 12,
  },
  settingsGroup: {
    width: "100%",
    gap: 10,
    marginTop: 6,
  },
  settingRow: {
    minHeight: 52,
    backgroundColor: "#fffaf0",
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  settingBlock: {
    backgroundColor: "#fffaf0",
    borderRadius: 17,
    padding: 11,
    gap: 8,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  settingLabel: {
    color: "#10251d",
    fontSize: 13,
    fontWeight: "900",
  },
  settingToggle: {
    width: 54,
    height: 30,
    borderRadius: 999,
    backgroundColor: "#d8c5a7",
    padding: 3,
    justifyContent: "center",
  },
  settingToggleOn: {
    backgroundColor: "#1f7a54",
  },
  settingToggleKnob: {
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  settingToggleKnobOn: {
    alignSelf: "flex-end",
  },
  settingSegment: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  settingSegmentButton: {
    flexGrow: 1,
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  settingSegmentButtonOn: {
    backgroundColor: "#17352a",
    borderColor: "#c9a45c",
  },
  settingSegmentText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  settingSegmentTextOn: {
    color: "#f5efe4",
  },
  rulesList: {
    width: "100%",
    gap: 9,
    marginVertical: 4,
  },
  ruleHelpItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "#fffaf0",
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  ruleHelpBadge: {
    minWidth: 46,
    minHeight: 36,
    borderRadius: 14,
    backgroundColor: "#17352a",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  ruleHelpBadgeText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  ruleHelpText: {
    flex: 1,
    color: "#5f5242",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  shopSheet: {
    gap: 12,
  },
  shopBalanceRow: {
    flexDirection: "row",
    gap: 8,
  },
  shopTabBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    backgroundColor: "#e7ded0",
    borderRadius: 18,
    padding: 5,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  shopTabButton: {
    flex: 1,
    minWidth: 82,
    minHeight: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  shopTabButtonActive: {
    backgroundColor: "#17352a",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  shopTabText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "900",
  },
  shopTabTextActive: {
    color: "#f5efe4",
  },
  shopSection: {
    backgroundColor: "#f5efe4",
    borderRadius: 20,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  shopSectionTitle: {
    color: "#8c6b33",
    fontWeight: "900",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  dailyRewardCard: {
    backgroundColor: "#2d6f92",
    borderRadius: 18,
    padding: 14,
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#7dd3fc",
  },
  dailyRewardCardClaimed: {
    backgroundColor: "#34515f",
    borderColor: "#7ea4b4",
  },
  dailyRewardTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  dailyRewardText: {
    color: "#dff7ff",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  dailyRewardValue: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
  },
  gemPurchaseCard: {
    minHeight: 86,
    backgroundColor: "#17352a",
    borderRadius: 18,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#8fc9a6",
  },
  shopActionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 17,
    backgroundColor: "rgba(245,239,228,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(245,239,228,0.2)",
  },
  shopActionIcon: {
    width: 36,
    height: 36,
  },
  shopActionTextBox: {
    flex: 1,
  },
  gemPurchaseTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  gemPurchaseText: {
    color: "#d9e8df",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
    lineHeight: 17,
  },
  exchangeCard: {
    backgroundColor: "#c9a45c",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#8c6b33",
  },
  exchangeIconRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  exchangeIcon: {
    width: 42,
    height: 42,
  },
  exchangeTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  exchangeText: {
    color: "#3b2417",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 3,
  },
  premiumPassCard: {
    backgroundColor: "#10251d",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  premiumPassTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  premiumPassText: {
    color: "#d8c5a7",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  cardBackCollectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  cardBackCollectionSubtitle: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  collectionPercentPill: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  collectionPercentText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  cardBackShowcase: {
    minHeight: 162,
    backgroundColor: "#10251d",
    borderRadius: 24,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "#c9a45c",
    overflow: "hidden",
  },
  cardBackShowcaseStack: {
    width: 118,
    height: 138,
    alignItems: "center",
    justifyContent: "center",
  },
  cardBackShowcaseImage: {
    position: "absolute",
    width: 84,
    height: 122,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#f5efe4",
    backgroundColor: "#10251d",
    shadowColor: "#000",
    shadowOpacity: 0.42,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 10,
    transform: [{ rotate: "0deg" }],
  },
  cardBackShowcaseGhost: {
    opacity: 0.52,
    transform: [{ translateX: -22 }, { rotate: "-10deg" }],
  },
  cardBackShowcaseGhostTwo: {
    opacity: 0.7,
    transform: [{ translateX: 22 }, { rotate: "10deg" }],
  },
  cardBackShowcaseCopy: {
    flex: 1,
    gap: 5,
  },
  cardBackShowcaseEyebrow: {
    color: "#d8c5a7",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  cardBackShowcaseTitle: {
    color: "#ffffff",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  cardBackShowcaseText: {
    color: "#d9e8df",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 18,
  },
  cardBackShowcaseBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(201,164,92,0.18)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.65)",
    marginTop: 3,
  },
  cardBackShowcaseBadgeText: {
    color: "#f5efe4",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  shopFeatureCard: {
    minHeight: 86,
    backgroundColor: "#fffaf0",
    borderRadius: 20,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  shopFeatureCardBuyable: {
    borderColor: "#c9a45c",
    backgroundColor: "#fff7df",
  },
  shopFeatureCardDisabled: {
    opacity: 0.72,
  },
  shopFeatureImage: {
    width: 46,
    height: 66,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d8c5a7",
    backgroundColor: "#10251d",
  },
  shopFeatureCopy: {
    flex: 1,
  },
  shopFeatureEyebrow: {
    color: "#8c6b33",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  shopFeatureTitle: {
    color: "#10251d",
    fontSize: 17,
    fontWeight: "900",
    marginTop: 2,
  },
  shopFeatureMeta: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
    marginTop: 3,
  },
  shopFeatureCta: {
    minWidth: 82,
    minHeight: 38,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  shopFeatureCtaStrong: {
    backgroundColor: "#17352a",
    borderColor: "#c9a45c",
  },
  shopFeatureCtaText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  shopFeatureCtaTextStrong: {
    color: "#ffffff",
  },
  cardBackFilterBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  cardBackFilterChip: {
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    paddingHorizontal: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  cardBackFilterChipOn: {
    backgroundColor: "#17352a",
    borderColor: "#c9a45c",
  },
  cardBackFilterText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  cardBackFilterTextOn: {
    color: "#f5efe4",
  },
  cardBackShopGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
  },
  cardBackShopItem: {
    width: "48%",
    minWidth: 146,
    backgroundColor: "#fbf8f1",
    borderRadius: 20,
    padding: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 5,
  },
  cardBackShopItemSelected: {
    backgroundColor: "#edf8ef",
    borderColor: "#1f7a54",
  },
  cardBackShopItemLocked: {
    opacity: 0.84,
  },
  cardBackShopItemBuyable: {
    borderColor: "#c9a45c",
    backgroundColor: "#fffaf0",
  },
  cardBackShopItemDisabled: {
    opacity: 0.68,
  },
  cardBackImageStage: {
    width: "100%",
    minHeight: 164,
    borderRadius: 17,
    backgroundColor: "#10251d",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.4)",
  },
  cardBackShopImage: {
    width: 104,
    height: 148,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#f5efe4",
    backgroundColor: "#10251d",
  },
  cardBackRarityBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "rgba(245,239,228,0.92)",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  cardBackRarityText: {
    color: "#17352a",
    fontSize: 8,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  cardBackShopTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
  },
  cardBackShopDescription: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 14,
    textAlign: "center",
    minHeight: 28,
  },
  cardBackPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#efe1c4",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  cardBackPriceIcon: {
    width: 16,
    height: 16,
  },
  cardBackPriceText: {
    color: "#6b512b",
    fontSize: 11,
    fontWeight: "900",
  },
  cardBackCta: {
    width: "100%",
    minHeight: 38,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  cardBackCtaSelected: {
    backgroundColor: "#1f7a54",
    borderColor: "#0f5138",
  },
  cardBackCtaOwned: {
    backgroundColor: "#17352a",
    borderColor: "#0b2b21",
  },
  cardBackCtaBuyable: {
    backgroundColor: "#c9a45c",
    borderColor: "#8c6b33",
    shadowColor: "#c9a45c",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 6,
  },
  cardBackCtaText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "900",
  },
  cardBackCtaTextStrong: {
    color: "#ffffff",
  },
  cardBackShopMeta: {
    color: "#6d614f",
    fontSize: 9,
    fontWeight: "900",
    textAlign: "center",
  },
  shopEmptyState: {
    minHeight: 86,
    borderRadius: 18,
    backgroundColor: "#efe7da",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cdbd9f",
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
  },
  shopEmptyTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  shopEmptyText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 3,
  },
  tableSkinGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
  },
  tableSkinCard: {
    width: "48%",
    minWidth: 146,
    backgroundColor: "#fbf8f1",
    borderRadius: 20,
    padding: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  tableSkinCardSelected: {
    backgroundColor: "#edf8ef",
    borderColor: "#1f7a54",
  },
  tableSkinCardBuyable: {
    backgroundColor: "#fffaf0",
    borderColor: "#c9a45c",
  },
  tableSkinCardDisabled: {
    opacity: 0.68,
  },
  tableSkinPreview: {
    height: 86,
    borderRadius: 18,
    backgroundColor: "#10251d",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.35)",
  },
  tableSkinFelt: {
    width: 92,
    height: 58,
    borderRadius: 18,
    borderWidth: 2,
  },
  tableSkinRail: {
    position: "absolute",
    width: 116,
    height: 78,
    borderRadius: 24,
    borderWidth: 3,
    opacity: 0.42,
  },
  tableSkinTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  tableSkinMeta: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  tableSkinCta: {
    minHeight: 36,
    borderRadius: 999,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  tableSkinCtaStrong: {
    backgroundColor: "#17352a",
    borderColor: "#c9a45c",
  },
  tableSkinCtaText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  tableSkinCtaTextStrong: {
    color: "#ffffff",
  },
  comingSoonCard: {
    minHeight: 170,
    backgroundColor: "#10251d",
    borderRadius: 24,
    padding: 18,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  comingSoonEyebrow: {
    color: "#d8c5a7",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  comingSoonTitle: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "900",
    marginTop: 4,
  },
  comingSoonText: {
    color: "#d9e8df",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
    marginTop: 6,
  },
  milestoneCard: {
    backgroundColor: "#fffaf0",
    borderRadius: 18,
    padding: 12,
    gap: 9,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  milestoneCardReady: {
    borderColor: "#1f7a54",
    backgroundColor: "#edf8ef",
  },
  milestoneCardClaimed: {
    opacity: 0.66,
  },
  milestoneTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  milestoneCopy: {
    flex: 1,
  },
  milestoneTitle: {
    color: "#10251d",
    fontSize: 15,
    fontWeight: "900",
  },
  milestoneText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  milestoneRewardPill: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  milestoneRewardText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  milestoneProgressTrack: {
    height: 9,
    backgroundColor: "#d8c5a7",
    borderRadius: 999,
    overflow: "hidden",
  },
  milestoneProgressFill: {
    height: "100%",
    backgroundColor: "#1f7a54",
    borderRadius: 999,
  },
  milestoneBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  milestoneProgressText: {
    color: "#6d614f",
    fontSize: 10,
    fontWeight: "900",
  },
  milestoneActionText: {
    color: "#1f7a54",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  quickRulesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
  },
  rulePill: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(201,164,92,0.45)",
  },
  rulePillText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  homeFooterText: {
    textAlign: "center",
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
  },
  lobbyScroll: {
    flexGrow: 1,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 24,
    justifyContent: "flex-start",
  },
  lobbyPanel: {
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
    backgroundColor: "#f5efe4",
    borderRadius: 30,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.7)",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 22,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 16,
  },
  lobbyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 14,
  },
  lobbyEyebrow: {
    color: "#8c6b33",
    fontWeight: "900",
    fontSize: 12,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  lobbyTitle: {
    color: "#10251d",
    fontSize: 31,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  lobbySubtitle: {
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
    maxWidth: 285,
  },
  playerCountPill: {
    backgroundColor: "#17352a",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 2,
    borderColor: "#c9a45c",
  },
  playerCountText: {
    color: "#f5efe4",
    fontWeight: "900",
    fontSize: 16,
  },
  codeHeroCard: {
    backgroundColor: "#17352a",
    borderRadius: 26,
    padding: 18,
    borderWidth: 1,
    borderColor: "#c9a45c",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.32,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 10,
  },
  codeLabel: {
    color: "#d8c5a7",
    fontWeight: "900",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  codeValue: {
    color: "#fbf8f1",
    fontWeight: "900",
    fontSize: 42,
    letterSpacing: 4,
    marginTop: 3,
  },
  codeActionsVertical: {
    gap: 8,
  },
  codeActionButton: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 999,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
  },
  codeActionText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 12,
  },
  codeActionButtonGold: {
    backgroundColor: "#c9a45c",
    borderRadius: 999,
    paddingHorizontal: 15,
    paddingVertical: 10,
    alignItems: "center",
  },
  codeActionTextGold: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 12,
  },
  roomStepCard: {
    minHeight: 66,
    backgroundColor: "#fffaf0",
    borderRadius: 21,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  roomStepBadge: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: "#17352a",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  roomStepBadgeText: {
    color: "#f5efe4",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  roomStepCopy: {
    flex: 1,
  },
  roomStepTitle: {
    color: "#10251d",
    fontSize: 18,
    fontWeight: "900",
  },
  roomStepText: {
    color: "#6d614f",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  lobbyStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  hostPill: {
    backgroundColor: "#ebe2d4",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  hostPillText: {
    color: "#6b512b",
    fontWeight: "900",
    fontSize: 12,
  },
  readyCard: {
    backgroundColor: "#ebe2d4",
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  readyTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  readyTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 15,
  },
  readyNumber: {
    color: "#1f7a54",
    fontWeight: "900",
    fontSize: 15,
  },
  progressTrack: {
    height: 11,
    backgroundColor: "#d8c5a7",
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 10,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#1f7a54",
    borderRadius: 999,
  },
  roomFactsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  roomFactChip: {
    backgroundColor: "#ebe2d4",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  roomFactText: {
    color: "#6d614f",
    fontSize: 11,
    fontWeight: "900",
  },
  readyHelper: {
    marginTop: 8,
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 12,
  },
  nameEditCard: {
    backgroundColor: "#fbf8f1",
    borderRadius: 20,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  nameEditHelper: {
    color: "#6d614f",
    fontWeight: "700",
    fontSize: 11,
  },
  profileLockedName: {
    color: "#10251d",
    fontSize: 20,
    fontWeight: "900",
  },
  playersSection: {
    backgroundColor: "#fbf8f1",
    borderRadius: 24,
    padding: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  playerListTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 4,
    paddingBottom: 2,
  },
  playerListTitle: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 16,
  },
  playerListMeta: {
    color: "#1f7a54",
    fontWeight: "800",
    fontSize: 12,
  },
  playerSlotCard: {
    width: "48%",
    minHeight: 142,
    backgroundColor: "#fbf8f1",
    borderRadius: 22,
    padding: 12,
    borderWidth: 1,
    borderColor: "#ded1bb",
    justifyContent: "space-between",
  },
  playerSlotReady: {
    backgroundColor: "#eef7f0",
    borderColor: "#8fc9a6",
  },
  playerSlotOffline: {
    opacity: 0.45,
  },
  emptySlotCard: {
    width: "48%",
    minHeight: 142,
    backgroundColor: "#efe7da",
    borderRadius: 22,
    padding: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cdbd9f",
    justifyContent: "center",
    alignItems: "center",
  },
  playerRowCard: {
    minHeight: 78,
    backgroundColor: "#ffffff",
    borderRadius: 19,
    padding: 11,
    borderWidth: 1,
    borderColor: "#ded1bb",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  playerRowMain: {
    flex: 1,
    gap: 5,
  },
  playerRowRight: {
    alignItems: "flex-end",
    justifyContent: "space-between",
    minHeight: 52,
  },
  emptySlotRow: {
    minHeight: 68,
    backgroundColor: "#efe7da",
    borderRadius: 18,
    padding: 11,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cdbd9f",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  emptySlotCopy: {
    flex: 1,
  },
  slotTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  slotAvatar: {
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: "#17352a",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#c9a45c",
  },
  slotAvatarText: {
    color: "#ffffff",
    fontSize: 21,
    fontWeight: "900",
  },
  slotStatusDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
  },
  slotStatusOnline: {
    backgroundColor: "#22c55e",
  },
  slotStatusOffline: {
    backgroundColor: "#ef4444",
  },
  slotName: {
    color: "#10251d",
    fontWeight: "900",
    fontSize: 16,
  },
  slotTags: {
    flexDirection: "row",
    gap: 5,
    flexWrap: "wrap",
    minHeight: 24,
  },
  hostTag: {
    backgroundColor: "#efe1c4",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  hostTagText: {
    color: "#6b512b",
    fontWeight: "900",
    fontSize: 10,
  },
  youTag: {
    backgroundColor: "#e6eee9",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  youTagText: {
    color: "#17352a",
    fontWeight: "900",
    fontSize: 10,
  },
  readyMiniBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#e7ded0",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  readyMiniBadgeOn: {
    backgroundColor: "#dcefe2",
  },
  readyMiniBadgeText: {
    color: "#6b7280",
    fontWeight: "900",
    fontSize: 11,
  },
  readyMiniBadgeTextOn: {
    color: "#1f7a54",
  },
  emptyAvatar: {
    width: 44,
    height: 44,
    borderRadius: 18,
    backgroundColor: "#e7ded0",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyAvatarText: {
    color: "#9ca3af",
    fontWeight: "900",
    fontSize: 24,
  },
  emptySlotTitle: {
    marginTop: 8,
    color: "#6b7280",
    fontWeight: "900",
  },
  emptySlotText: {
    color: "#9ca3af",
    fontWeight: "800",
    fontSize: 12,
  },
  lobbyBottomPanel: {
    backgroundColor: "#fbf8f1",
    borderRadius: 26,
    padding: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "#ded1bb",
  },
  readyCtaButton: {
    backgroundColor: "#ffffff",
    minHeight: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d8c5a7",
  },
  readyCtaButtonOn: {
    backgroundColor: "#dcefe2",
    borderColor: "#1f7a54",
  },
  readyCtaText: {
    color: "#374151",
    fontWeight: "900",
    fontSize: 16,
  },
  readyCtaTextOn: {
    color: "#1f7a54",
  },
  hostControlNotice: {
    minHeight: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e6eee9",
    borderWidth: 1,
    borderColor: "#8fc9a6",
    paddingHorizontal: 14,
  },
  hostControlNoticeText: {
    color: "#17352a",
    fontWeight: "800",
    textAlign: "center",
  },
  startButton: {
    backgroundColor: "#17352a",
    minHeight: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#0b2b21",
  },
  startButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 17,
  },
  hostWaitingBox: {
    minHeight: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e7ded0",
  },
  hostWaitingText: {
    color: "#6b7280",
    fontWeight: "900",
  },
  leaveButtonWide: {
    minHeight: 44,
    backgroundColor: "rgba(239,68,68,0.10)",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.30)",
  },
  leaveButtonText: {
    color: "#ef4444",
    fontWeight: "900",
    fontSize: 13,
  },
});
