import { StyleSheet } from "react-native";

export const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(3,10,8,0.78)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 390,
    backgroundColor: "#f5efe4",
    borderRadius: 24,
    padding: 22,
    gap: 14,
    borderWidth: 1,
    borderColor: "#c9a45c",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 18,
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: "900",
    textAlign: "center",
    color: "#10251d",
  },
  modalText: {
    textAlign: "center",
    color: "#5f5242",
    fontWeight: "700",
  },
  modalSuitGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  modalSuitButton: {
    width: "48%",
    minHeight: 112,
    backgroundColor: "#fbf8f1",
    borderWidth: 1,
    borderColor: "#c9a45c",
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  modalSuitIcon: {
    fontSize: 36,
    fontWeight: "900",
    textAlign: "center",
  },
  modalSuitText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#10251d",
    textAlign: "center",
  },
  modalYesButton: {
    backgroundColor: "#1f7a54",
    borderRadius: 15,
    paddingVertical: 13,
    alignItems: "center",
    minHeight: 50,
    justifyContent: "center",
  },
  modalYesButtonText: {
    color: "#ffffff",
    fontWeight: "900",
  },
  cancelButton: {
    backgroundColor: "#e7ded0",
    borderRadius: 15,
    paddingVertical: 12,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#17352a",
    fontWeight: "900",
  },
  voteText: {
    textAlign: "center",
    color: "#6b7280",
    fontWeight: "800",
    fontSize: 12,
  },
});
