import { StyleSheet } from "react-native";

export const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(3,10,8,0.84)",
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
  },
  modalCard: {
    width: "100%",
    maxWidth: 390,
    backgroundColor: "#fff7e7",
    borderRadius: 28,
    padding: 22,
    gap: 14,
    borderWidth: 3,
    borderColor: "#f1c75b",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: {
      width: 0,
      height: 16,
    },
    elevation: 18,
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: "900",
    textAlign: "center",
    color: "#10251d",
  },
  modalText: {
    textAlign: "center",
    color: "#5f5242",
    fontWeight: "700",
  },
  modalSuitGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  modalSuitButton: {
    width: "48%",
    minHeight: 112,
    backgroundColor: "#fbf8f1",
    borderWidth: 2,
    borderColor: "#d6b35c",
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  modalSuitIcon: {
    fontSize: 36,
    fontWeight: "900",
    textAlign: "center",
  },
  modalSuitText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#10251d",
    textAlign: "center",
  },
  modalYesButton: {
    backgroundColor: "#178a57",
    borderRadius: 18,
    paddingVertical: 13,
    alignItems: "center",
    minHeight: 50,
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#063e28",
  },
  modalYesButtonText: {
    color: "#ffffff",
    fontWeight: "900",
  },
  cancelButton: {
    backgroundColor: "#e7ded0",
    borderRadius: 15,
    paddingVertical: 12,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#17352a",
    fontWeight: "900",
  },
  voteText: {
    textAlign: "center",
    color: "#6b7280",
    fontWeight: "800",
    fontSize: 12,
  },
  gameModalFrame: {
    width: "100%",
    maxWidth: 430,
    maxHeight: "92%",
    backgroundColor: "#fff7e7",
    borderRadius: 31,
    padding: 16,
    gap: 13,
    borderWidth: 3,
    borderColor: "#f1c75b",
    shadowColor: "#000",
    shadowOpacity: 0.36,
    shadowRadius: 26,
    shadowOffset: {
      width: 0,
      height: 18,
    },
    elevation: 22,
  },
  gameModalFrameDark: {
    backgroundColor: "#071c18",
    borderColor: "#f1c75b",
  },
  gameModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  gameModalTitleBlock: {
    flex: 1,
    gap: 3,
  },
  gameModalEyebrow: {
    color: "#9a7429",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.35,
    textTransform: "uppercase",
  },
  gameModalEyebrowDark: {
    color: "#f8d469",
  },
  gameModalTitle: {
    color: "#10251d",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 0,
  },
  gameModalTitleDark: {
    color: "#ffffff",
  },
  gameModalText: {
    color: "#695d4d",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  gameModalTextDark: {
    color: "#d8c5a7",
  },
  gameModalCloseButton: {
    minHeight: 38,
    paddingHorizontal: 13,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(16,37,29,0.1)",
    borderWidth: 1,
    borderColor: "rgba(16,37,29,0.18)",
  },
  gameModalCloseButtonDark: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  gameModalCloseText: {
    color: "#10251d",
    fontSize: 11,
    fontWeight: "900",
  },
  gameModalCloseTextDark: {
    color: "#fff7e7",
  },
  gameActionButton: {
    minHeight: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#f4b739",
    borderWidth: 3,
    borderColor: "#7c4f12",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 8,
  },
  gameActionButtonSecondary: {
    backgroundColor: "#f6efe1",
    borderColor: "#c9a45c",
  },
  gameActionButtonDanger: {
    backgroundColor: "#301b18",
    borderColor: "#b94c4c",
  },
  gameActionButtonPressed: {
    transform: [{ translateY: 2 }, { scale: 0.985 }],
    shadowOpacity: 0.12,
  },
  gameActionButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.35)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  gameActionButtonTextDark: {
    color: "#10251d",
    textShadowColor: "transparent",
  },
  gameActionButtonSubText: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 10,
    fontWeight: "900",
    marginTop: -1,
    textTransform: "uppercase",
  },
  gameActionButtonSubTextDark: {
    color: "#7d6330",
  },
});
