import { StyleSheet } from "react-native";

import { calmTheme } from "../theme";

export const onboardingStyles = StyleSheet.create({
  onboardingShell: {
    flex: 1,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
  },
  onboardingScroll: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 24,
    justifyContent: "space-between",
    gap: 18,
  },
  onboardingTop: {
    alignItems: "center",
    gap: 8,
    paddingTop: 10,
  },
  onboardingLogoMark: {
    width: 70,
    height: 70,
    borderRadius: 26,
    backgroundColor: calmTheme.colors.accent,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.45)",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 8,
  },
  onboardingLogoText: {
    color: "#10201d",
    fontSize: 36,
    fontWeight: "900",
  },
  onboardingEyebrow: {
    color: calmTheme.colors.accentStrong,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    marginTop: 4,
  },
  onboardingTitle: {
    color: calmTheme.colors.textOnDark,
    fontSize: 34,
    fontWeight: "900",
    textAlign: "center",
  },
  onboardingSubtitle: {
    color: calmTheme.colors.textOnDarkMuted,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 19,
    maxWidth: 320,
  },
  onboardingCard: {
    borderRadius: 24,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 14,
    },
    elevation: 12,
  },
  onboardingLoadingCard: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingLoadingText: {
    color: calmTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  onboardingPrimaryButton: {
    minHeight: 62,
    borderRadius: 18,
    backgroundColor: calmTheme.colors.accent,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#8a6420",
    paddingHorizontal: 14,
  },
  onboardingPrimaryText: {
    color: "#10201d",
    fontSize: 18,
    fontWeight: "900",
  },
  onboardingPrimarySubText: {
    color: "#5c3c18",
    fontSize: 10,
    fontWeight: "900",
    marginTop: 2,
    textTransform: "uppercase",
  },
  onboardingPlaceholderButton: {
    minHeight: 56,
    borderRadius: 17,
    backgroundColor: calmTheme.colors.surfaceDark,
    paddingHorizontal: 14,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: calmTheme.colors.borderDark,
  },
  onboardingPlaceholderTitle: {
    color: calmTheme.colors.textOnDark,
    fontSize: 15,
    fontWeight: "900",
  },
  onboardingPlaceholderText: {
    color: calmTheme.colors.textOnDarkMuted,
    fontSize: 10,
    fontWeight: "800",
    marginTop: 2,
  },
  onboardingTutorialButton: {
    minHeight: 66,
    borderRadius: 18,
    backgroundColor: "rgba(16,32,29,0.06)",
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
  },
  onboardingTutorialIcon: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: calmTheme.colors.secondarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingTutorialIconText: {
    color: calmTheme.colors.text,
    fontSize: 20,
    fontWeight: "900",
  },
  onboardingTutorialCopy: {
    flex: 1,
    minWidth: 0,
  },
  onboardingTutorialTitle: {
    color: calmTheme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  onboardingTutorialText: {
    color: calmTheme.colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 16,
    marginTop: 2,
  },
  onboardingTermsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingTop: 2,
  },
  onboardingCheckbox: {
    width: 26,
    height: 26,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    backgroundColor: "#fffdf7",
    alignItems: "center",
    justifyContent: "center",
  },
  onboardingCheckboxChecked: {
    backgroundColor: calmTheme.colors.secondary,
    borderColor: "#2d7657",
  },
  onboardingCheckboxText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "900",
  },
  onboardingTermsText: {
    flex: 1,
    color: calmTheme.colors.text,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  onboardingLegalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  onboardingLegalText: {
    color: calmTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "900",
    textDecorationLine: "underline",
  },
  onboardingLegalDivider: {
    color: calmTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  onboardingNotice: {
    backgroundColor: "rgba(247,243,236,0.95)",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  onboardingNoticeText: {
    color: calmTheme.colors.text,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  tutorialShell: {
    flex: 1,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
    padding: 14,
    gap: 12,
    justifyContent: "space-between",
  },
  tutorialTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
  },
  tutorialProgressText: {
    color: calmTheme.colors.textOnDarkMuted,
    fontSize: 12,
    fontWeight: "900",
  },
  tutorialSkipButton: {
    minHeight: 38,
    borderRadius: 999,
    backgroundColor: "rgba(247,243,236,0.12)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  tutorialSkipText: {
    color: calmTheme.colors.textOnDark,
    fontSize: 12,
    fontWeight: "900",
  },
  tutorialStage: {
    flex: 1,
    minHeight: 280,
    justifyContent: "center",
    gap: 14,
  },
  tutorialOpponentRow: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    opacity: 0.76,
  },
  tutorialAvatar: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: calmTheme.colors.surfaceMuted,
  },
  tutorialCardBack: {
    width: 34,
    height: 48,
    borderRadius: 8,
    backgroundColor: calmTheme.colors.accent,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.36)",
  },
  tutorialTable: {
    minHeight: 160,
    borderRadius: 34,
    borderWidth: 4,
    borderColor: "rgba(210,168,78,0.7)",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 22,
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    elevation: 10,
  },
  tutorialDrawPile: {
    width: 72,
    height: 98,
    borderRadius: 14,
    backgroundColor: "#0f2922",
    borderWidth: 2,
    borderColor: calmTheme.colors.borderDark,
    alignItems: "center",
    justifyContent: "center",
  },
  tutorialPileText: {
    color: calmTheme.colors.textOnDarkMuted,
    fontSize: 13,
    fontWeight: "900",
  },
  tutorialDiscardPile: {
    width: 78,
    height: 108,
    borderRadius: 15,
    backgroundColor: calmTheme.colors.surface,
    borderWidth: 2,
    borderColor: calmTheme.colors.accent,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "4deg" }],
  },
  tutorialDiscardText: {
    color: calmTheme.colors.text,
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
  },
  tutorialHandRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  tutorialHandCard: {
    width: 48,
    height: 68,
    borderRadius: 11,
    backgroundColor: calmTheme.colors.surface,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  tutorialHandCardActive: {
    borderColor: calmTheme.colors.accent,
    backgroundColor: calmTheme.colors.accentSoft,
    transform: [{ translateY: -8 }],
  },
  tutorialHandCardText: {
    color: calmTheme.colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  tutorialCoachCard: {
    borderRadius: 24,
    padding: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
  },
  tutorialCoachEyebrow: {
    color: "#9a7429",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  tutorialCoachTitle: {
    color: calmTheme.colors.text,
    fontSize: 24,
    fontWeight: "900",
  },
  tutorialCoachText: {
    color: calmTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
  },
  tutorialActionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
  },
  tutorialSecondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: calmTheme.colors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  tutorialSecondaryText: {
    color: calmTheme.colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  tutorialPrimaryButton: {
    flex: 1.4,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: calmTheme.colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  tutorialPrimaryText: {
    color: calmTheme.colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
});
