import { StyleSheet } from "react-native";
import { calmTheme } from "../theme";

export const sharedStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: calmTheme.colors.background,
  },
  background: {
    flex: 1,
    overflow: "hidden",
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -130,
    right: -90,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: "rgba(210,168,78,0.08)",
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: -150,
    left: -110,
    width: 310,
    height: 310,
    borderRadius: 999,
    backgroundColor: "rgba(111,174,148,0.07)",
  },
  backgroundCoin: {
    position: "absolute",
    top: 92,
    left: -34,
    width: 96,
    height: 96,
    borderRadius: 999,
    backgroundColor: "rgba(210,168,78,0.07)",
    borderWidth: 10,
    borderColor: "rgba(210,168,78,0.08)",
    transform: [{ rotate: "-18deg" }],
  },
  backgroundCoinSmall: {
    position: "absolute",
    right: 22,
    bottom: 90,
    width: 46,
    height: 46,
    borderRadius: 999,
    backgroundColor: "rgba(247,243,236,0.05)",
    borderWidth: 5,
    borderColor: "rgba(210,168,78,0.09)",
  },
  screenTransition: {
    flex: 1,
  },
  keyboardScreen: {
    flex: 1,
  },
  connectionPill: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#edf7f0",
    paddingVertical: 8,
    paddingHorizontal: 13,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#c8ded1",
  },
  connectionPillDark: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(6,20,15,0.88)",
    paddingVertical: 8,
    paddingHorizontal: 13,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  connectionDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  connectionDotOn: {
    backgroundColor: "#22c55e",
  },
  connectionDotOff: {
    backgroundColor: "#ef4444",
  },
  connectionText: {
    color: "#17352a",
    fontWeight: "800",
    fontSize: 12,
  },
  connectionTextDark: {
    color: "#f7f1e8",
    fontWeight: "800",
    fontSize: 12,
  },
  inputLabel: {
    color: "#17352a",
    fontWeight: "800",
    fontSize: 13,
  },
  input: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d8c5a7",
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    fontSize: 16,
    color: "#111827",
    fontWeight: "700",
  },
  codeInput: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#bfa77f",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 24,
    color: "#111827",
    fontWeight: "800",
    letterSpacing: 3,
    textAlign: "center",
  },
  disabledButton: {
    opacity: 0.45,
  },
  errorBanner: {
    backgroundColor: "#fff1f2",
    borderWidth: 1,
    borderColor: "#fda4af",
    borderRadius: 16,
    paddingVertical: 11,
    paddingHorizontal: 13,
  },
  errorBannerText: {
    color: "#991b1b",
    fontWeight: "900",
    fontSize: 12,
    textAlign: "center",
  },
  loadingBanner: {
    backgroundColor: "#ecfdf5",
    borderWidth: 1,
    borderColor: "#a7f3d0",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 13,
  },
  loadingBannerText: {
    color: "#065f46",
    fontWeight: "900",
    fontSize: 12,
    textAlign: "center",
  },
  surfaceCard: {
    backgroundColor: calmTheme.colors.surface,
    borderRadius: calmTheme.radius.xl,
    padding: calmTheme.spacing.lg,
    borderWidth: 1,
    borderColor: calmTheme.colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 3,
  },
  surfaceCardSubdued: {
    backgroundColor: "rgba(247,243,236,0.92)",
    shadowOpacity: 0.04,
    elevation: 1,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: calmTheme.spacing.md,
  },
  sectionHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  sectionTitle: {
    color: calmTheme.colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  sectionSubtitle: {
    color: calmTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    marginTop: 2,
  },
  sectionAction: {
    minHeight: 32,
    borderRadius: calmTheme.radius.pill,
    paddingHorizontal: calmTheme.spacing.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: calmTheme.colors.surfaceMuted,
  },
  sectionActionText: {
    color: calmTheme.colors.text,
    fontSize: 11,
    fontWeight: "900",
  },
});
